### DISCUSSION TITLE
docker-compose file

### DISCUSSION THREAD

**Discussion by chris-befoul** [apache/superset#18069] [Q&A / Help] [answered]
Following the template outlined in the official docs for making a docker-compose file for alerts, scheduling and emailing. What is the purpose of the Postgres image being built in this file? What is it being used for?

**Comment by 1c7** [comment, marked as answer]
Hi, I am also a Superset user. (I haven't contribute any code to Superset yet)
I am gonna assume you are talking about `docker-compose-non-dev.yml` in the root folder. 
in that case, base on these 3 files from Superset 1.4.1 source code:   

* `docker-compose-non-dev.yml`
* `docker/pythonpath_dev/superset_config.py`
* `docker/.env-non-dev`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1804755/154644603-1038d59d-73d4-451b-8991-b0068501eb1b.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1804755/154644836-51232599-7977-44e6-9c5d-20be0f9378ea.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1804755/154644906-9c087f92-c5b5-4cdb-a8e0-ea6d5ee7b7cd.png">

# You can see that PostgreSQL is set to `SQLALCHEMY_DATABASE_URI`，
# [Configuring Superset](https://superset.apache.org/docs/installation/configuring-superset/)
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1804755/154645258-f381ece1-3f95-4eb4-8d46-f00e2549e254.png">

# Conclusion
This following code section in `docker-compose-non-dev.yml` is for `SQLALCHEMY_DATABASE_URI`
```
  db:
    env_file: docker/.env-non-dev
    image: postgres:10
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
```

Therefore, the service "db"(a PostgreSQL database) is for storing Superset metadata.
