### DISCUSSION TITLE
Superset redirects to http from https

### DISCUSSION THREAD

**Discussion by cintoSunny** [apache/superset#18330] [Q&A / Help]
We have deployed superset to an EKS cluster. We want TLS terminated at the Ingress controller.
This is how I set up the entire setup.
`GSLB Vip → Nginx ingress controller → http → ingress → service → pod`

When we enter the URL/login/ on the browser, it gets redirected to `login` again after we provide the credentials. On a new tab if I then open `/superset/welcome` it works just fine. We assume the problem is because Superset redirects initially to http from https, and the login in inaccessible, but I could be wrong

When we curl the WIP, this is the response
```
curl -ivk https://superset-aws-ssl.g.xx.com
*   Trying 10.20.xx.66...
* TCP_NODELAY set
* Connected to superset-aws-ssl.g.xx.com (10.20.xx.66) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / xxx-xxx-xxx-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=superset-aws-ssl.g.xx.com; OU=xx; O=YY Inc.; ST=CC; C=US
*  start date: Oct 13 20:01:12 2021 GMT
*  expire date: Nov 12 20:01:11 2023 GMT
*  issuer: CN=xx CA 1; OU=Certification Authority; O=xx; C=US
*  SSL certificate verify ok.
> GET / HTTP/1.1
> Host: superset-aws-ssl.g.xx.com
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 302 FOUND
HTTP/1.1 302 FOUND
< Server: nginx/1.17.8
Server: nginx/1.17.8
< Date: Fri, 15 Oct 2021 01:42:21 GMT
Date: Fri, 15 Oct 2021 01:42:21 GMT
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8
< Content-Length: 243
Content-Length: 243
< Connection: keep-alive
Connection: keep-alive
< Location: http://superset-aws-ssl.g.xx.com/superset/welcome/
Location: http://superset-aws-ssl.g.xx.com/superset/welcome/

< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>Redirecting...</title>
<h1>Redirecting...</h1>

```
In the above curl, we see that the location is getting redirected to HTTP. 

This is the ingress controller yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-Proto: $scheme";
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:vvvv:certificate/xx-x-x-x-xxx
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
  resourceVersion: "6835154"
  selfLink: /api/v1/namespaces/ingress-nginx/services/ingress-nginx
  uid: xx-xx-xx-xx-xxxxx
spec:
  clusterIP: xx.xxx.xxx.xxx
  externalTrafficPolicy: Local
  healthCheckNodePort: 30599
  ports:
  - name: http
    nodePort: 31840
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30330
    port: 443
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
```

This is the ingress on top of the superset service:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-Proto: https";
  name: superset-ingress
  namespace: superset-ssl-v2
spec:
  rules:
  - host: https://superset-aws-ssl.g.xx.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          serviceName: superset
          servicePort: 8080
```

When we port forward the service, it works just fine.

**Comment by nogreintel** [comment]
I am also experiencing the same issue

**Comment by ajayy1608** [comment]
@cintoSunny There is one mistake I see in your annotations. Actually the doc mentions to add a request header while the `more_set_headers` add a response header. Below configurations changes worked for me:

1. Add request headers using custom configmap as per nginx ingress documentation:
```
apiVersion: v1
data:
  X-Forwarded-Proto: "https"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
```
2. Refer to the above custom configmap in the configmap passed to nginx-ingress command (`--configmap=$(POD_NAMESPACE)/ingress-nginx-controller`). `proxy-set-headers` is the important part here which sets it as request header:
```
apiVersion: v1
data:
  proxy-set-headers: "ingress-nginx/custom-headers"
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
```
3. Add below flags to superset config:
```
ENABLE_PROXY_FIX = True
PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 0, "x_prefix": 1}
```
I'm setting `"x_port": 0` in PROXY_FIX_CONFIG without which I was getting Location as https://superset.example.com:80/. This combination of 3 changes fixed it form me.

**Reply by emrekmrc** [reply]
why is your target port is http ? it should be https

- name: https
    nodePort: 30330
    port: 443
    protocol: TCP
    targetPort: http -> https

**Comment by diegoquintanav** [comment]
Just to extend on this answer. I'm using k3s with superset behind traefik and mostly vanilla settings and with ony port 443 open, and this answer helped me

https://github.com/apache/superset/issues/17126#issuecomment-1000519393

specifically, adding to my helm deployment the following

```yaml
configOverrides:
  # OTHER CONFIG OVERRIDES GO HERE
  # [load balancer / proxy / envoy / kong / ...] timeout settings.
  # Use all X-Forwarded headers when ENABLE_PROXY_FIX is True.
  # When proxying to a different port, set "x_port" to 0 to avoid downstream issues.
  extend_load_balancer: |
      # https://superset.apache.org/docs/installation/configuring-superset/#configuration-behind-a-load-balancer
      ENABLE_PROXY_FIX = True
      PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 1, "x_prefix": 1}
```

**Comment by bweigel** [comment]
That was a really tough nut to crack. I only had the issue in one case - "deleting tags". In the frontend this would generate a [`DELETE` request without a trailing slash](https://github.com/apache/superset/blob/2a9a1d3194b5cd6ae6e727aacc61d8a14ad78fe8/superset-frontend/src/features/tags/tags.ts#L114-L117). The slash would be appended by Werkzeug's [`append_slash_redirect`](https://github.com/pallets/werkzeug/blob/9e050f7750214d6779636813b8d661250804e811/src/werkzeug/utils.py#L282), returning a 308 with a Location header set to `http` instead of the original `https`. I tried most of the things above, but to no avail. The location header would always have `http` set as scheme.

I couldn't change config maps in our setup and ended up working with annotations on the `Ingress` to [rewrite the location header](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#proxy-redirect) from the backend responses:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers "X-Forwarded-Proto: https";'
    nginx.ingress.kubernetes.io/proxy-redirect-from: http://$host
    nginx.ingress.kubernetes.io/proxy-redirect-to: https://$host
  labels:
    app: superset
    chart: superset-0.12.4
    heritage: Helm
    release: superset
  name: superset
  namespace: data
spec:
  ingressClassName: nginx
  rules:
    - host: superset.mycorp.internal
      http:
        paths:
          - backend:
              service:
                name: superset
                port:
                  name: http
            path: /
            pathType: Prefix
```
