### DISCUSSION TITLE
[1.4.1] VERSIONED_EXPORT is generating wrong "extra" type (string) in dataset

### DISCUSSION THREAD

**Discussion by zedlauzy** [apache/superset#18808] [Q&A / Help] [answered]
Hi there, I am observing that some of my exported dataset yaml contains `extra` with value `'{"warning_markdown":null}'` after I migrated to 1.4.1. This results to `'columns': {0: {'extra': ['Not a valid mapping type.']}` ValidationError during import of these yaml files (in [validate objects](https://github.com/apache/superset/blob/1.4/superset/commands/importers/v1/__init__.py#L100)). 

The mentioned dataset is updated after the 1.4.1 migration (with no change in `extra`) and after comparing with the exported yaml with 1.2, I see that `extra` does not exist in the 1.2 yaml, thus it is probably newly added in 1.4.1 export yaml.

I believe `extra` should be an object as I do observe that I do have a `extra:
    warning_markdown: ''` in `metrics` which does not have validation issue. 

(Edit) Interestingly enough, a dataset which is not edited after 1.4.1 migration has `extra: null` and import is working as expected

Could I get advice on a temporary fix? Below is a brief sample of the 1.4.1 yaml file:

```
metrics:
- metric_name: count
  verbose_name: null
  metric_type: null
  expression: count(*)
  description: null
  d3format: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: CREATED_AT
  verbose_name: null
  is_dttm: true
  is_active: null
  type: DATETIME
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: '{"warning_markdown":null}'
```
