### DISCUSSION TITLE
SSL with NLB and ACM on EKS

### DISCUSSION THREAD

**Discussion by whitney** [apache/superset#19785] [Q&A / Help]
Hello all (apologies for all the acronyms), I am struggling to get SSL working on a superset cluster running on AWS EKS. The goal is to have nodes deployed in a private subnet, while superset is made available to the internet via NLB. Per the [superset helm documentation](https://superset.apache.org/docs/installation/running-on-kubernetes/), I have chosen to make superset available via a `LoadBalancer` service.

My setup is as follows:
* EKS cluster with nodes deployed in private subnet of VPC
* ACM cert for SSL
* gunicorn listening on port 80 (the idea is that SSL termination happens at the NLB)
* LoadBalancer Service definition as follows:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: superset-staging
  labels:
    app: superset
    chart: superset-0.5.10
    release: superset-staging
    heritage: Helm
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:*:*:certificate/*
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: superset
    release: superset-staging
```

After running `helm upgrade ... --install ...`, the NLB is provisioned with the appropriate ACM cert, but when I point an A-record at it and visit it at https://..., the gunicorn nodes are never hit and the server sends back an empty response. 

**Update:** Just to rule out cluster configuration issues, using the same cluster but with _no SSL_--ie ports above all set to 80, and no certificate or ssl port annotations--the superset UI was accessible via HTTP.

Have folks had any luck with this? Ty in advance.

**Comment by whitney** [comment]
I up switching to an ingress (alb), which worked fine.

**Reply by Aliaksei-Surautsau** [reply]
@whitney could you please share ingress example ? I faced with issue linked with "302" in ALB

**Reply by iamrohit07** [reply]
@whitney @Aliaksei-Surautsau  Were you guys able to get it working with AWS ALB. I am facing redirect issues on user/list page. Any help would be appreciated.

**Reply by Aliaksei-Surautsau** [reply]
I found the issue. when using this :   

  ```
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/group.name: xxxx
        alb.ingress.kubernetes.io/target-type: yyyy
        alb.ingress.kubernetes.io/scheme: internal
        alb.ingress.kubernetes.io/certificate-arn: xxxx
        alb.ingress.kubernetes.io/target-node-labels:yyyy
        alb.ingress.kubernetes.io/subnets: 123123123
        alb.ingress.kubernetes.io/healthcheck-path: /health
      hosts:
        - superset.xxx.com
      paths:
        - /*
```

  the path in ALB was not ` /*`
 it was `/`
 so I fixed manually ALB path in AWS to  `/* `
and it start working. I didnt check in details why helm of superset create only `/` , could be issue from my side .
