### DISCUSSION TITLE
Helm chart support mysql

### DISCUSSION THREAD

**Discussion by canghai118** [apache/superset#21085] [General]
We are deploying superset use helm charts, in the current version of helm chart,  Postgresql is hard coded in config files. It is inconvenient for user to configure an external mysql database for superset metastore.   I think we should change the helm chart to support  other database type, include mysql and sqlite

https://github.com/apache/superset/blob/master/helm/superset/templates/_helpers.tpl#L82

**Comment by jimyag** [comment]
```yaml
configOverrides:
  mysql: |
    SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://username:password@mysqlhostname:3306/superset'
....

postgresql:
  # disable pg
  enabled: false

supersetNode:
  connections:
        db_host: "mysqlhostname"
        db_port: "3306"
        db_user: username
        db_pass: password
        db_name: superset
bootstrapScript：|
  pip install PyMySQL
```
