### DISCUSSION TITLE
helm installs version 0.0.0.dev

### DISCUSSION THREAD

**Discussion by eyerra** [apache/superset#21599] [Q&A / Help]
Hi there,
Please help me installing latest version of Apache Superset in my EKS cluster. 
Currently I am installing Superset using helm chart with below parameters
```
        image:
          repository: apache/superset
          tag: latest
          pullPolicy: Always
```
and when I tried to access the superset, it shows the version as 0.0.0.dev (Navigate to Settings=>About). How can I install the latest version?
