### DISCUSSION TITLE
Deploy Superset in Docker swarm mode (with docker stack deploy)

### DISCUSSION THREAD

**Discussion by aleksvujic** [apache/superset#22519] [Q&A / Help]
Your documentation only provides examples and configuration for deploying Superset with `docker-compose up`. I believe many of us would like to use `docker stack deploy -c docker-compose.yml Superset` command to deploy Superset as a stack of services.

Our use case is deploying Superset behind [Traefik](https://github.com/traefik/traefik) reverse proxy which requires specifying `label`s for the Docker service.

Can you please provide an example on how to deploy Superset with `docker stack deploy`?

**Comment by rusackas** [comment]
I'm not sure off the top of my head, but I'll ping @craig-rueda and @hughhhh here to see if they have any input.

It might also be worth asking this in the #deploying-superset channel on [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw)

**Comment by anthonyorona** [comment]
Is there support for running superset as a docker stack?

**Comment by bgalvao** [comment]
Well, I am also looking into this. But if anyone can do the groundwork, I will highly appreciate it!

**Comment by bgalvao** [comment]
Ok y'all, I managed to make it work, at least locally by mapping `superset.some.domain` to `127.0.0.1` in  `/etc/hosts`. Here goes

# Superset x Traefik

<details><summary>`traefik.yml`</summary>
    
```yaml
version: '3.8'

networks:
  proxy:
    external: true

volumes:
  traefik_log:

services:

  traefik:
    image: $TRAEFIK_REGISTRY_TAG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_log:/var/log
    networks:
      - proxy
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        traefik.http.services.traefik.loadbalancer.server.port: 80
        
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.network=proxy

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443

      - --log=true
      - --log.format=json
      - --log.level=ERROR
      - --log.filepath=/var/log/traefik.log

      - --accesslog=true
      - --accesslog.filepath=/var/log/access.log
      - --accesslog.format=json

    ports:
      - 80:80    # http
      - 8080:8080
      - 443:443  # https entrypoint

```
    
</details>

<details><summary>`superset.yml`</summary>

```yaml
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
x-superset-image: &superset-image apache/superset
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false

networks:
  proxy:
    external: true
  superset:


version: "3.7"
services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - superset

  db:
    env_file: docker/.env-non-dev
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
    networks:
      - superset

  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    deploy:
      labels:
        traefik.http.routers.superset.rule: Host(`superset.${DOMAIN}`)
        traefik.http.routers.superset.tls: 'true'
        # port discovery in swarm mode
        traefik.http.services.superset.loadbalancer.server.port: 8088
    networks:
      - superset
      - proxy

  superset-init:
    image: *superset-image
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env-non-dev
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks:
      - superset

  superset-worker:
    image: *superset-image
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"]
    networks:
      - superset

  superset-worker-beat:
    image: *superset-image
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks:
      - superset
```
    
</details>


Note that, in my set up, I have an attachable overlay network `proxy` (referred to as being external in the compose files) that was spun up with the following command

```shell
docker network create --attachable --driver overlay proxy
```

- All of the reverse-proxied services go in that network.
- Otherwise, if there is an application that is composed by several services, like Superset, I put them in their own isolated network, `superset`, which is created dynamically when you create the stack

Then all you have to do, of course, is to

```shell
export DOMAIN=some.domain
docker stack deploy -c traefik.yml traefik
docker stack deploy -c superset.yml superset
```
