### DISCUSSION TITLE
Scheduled Email Reporting

### DISCUSSION THREAD

**Discussion by adimyth** [apache/superset#22680] [Q&A / Help]
I am trying to enable email reporting in the apache superset. I have followed the instructions specified in the [official docs](https://superset.apache.org/docs/installation/alerts-reports). However, I haven't been able to make it work at all.
My setup looks as follows -

**_Superset Config_**

```python
import logging
import os
from typing import Optional

from cachelib.file import FileSystemCache  # type: ignore
from celery.schedules import crontab  # type: ignore

logger = logging.getLogger()


def get_env_variable(var_name: str, default: Optional[str] = None) -> str:
    """Get the environment variable or raise exception."""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        else:
            error_msg = (
                "[ERROR] The environment variable {} was missing, abort...".format(
                    var_name
                )
            )
            raise EnvironmentError(error_msg)


#################################
#       ESSENTIAL CONFIGS       #
#################################
SECRET_KEY = get_env_variable("SECRET_KEY")
ALERT_REPORTS_NOTIFICATION_DRY_RUN = False


###################################
#           FEATURE FLAGS         #
###################################
FEATURE_FLAGS = {
    "ALERT_REPORTS": True,
    "EMBEDDED_SUPERSET": True,
    "ENABLE_TEMPLATE_PROCESSING": True,
    "DRILL_TO_DETAIL": True,
    "DASHBOARD_CROSS_FILTERS": True,
    "ENABLE_JAVASCRIPT_CONTROLS": True,
    "ENABLE_FILTER_BOX_MIGRATION": True,
    "UX_BETA": True,
}


#################################
#       METADATA DATABASE       #
#################################
DATABASE_DIALECT = get_env_variable("DB_DIALECT")
DATABASE_USER = get_env_variable("DB_USER")
DATABASE_PASSWORD = get_env_variable("DB_PASSWORD")
DATABASE_HOST = get_env_variable("DB_HOST")
DATABASE_PORT = get_env_variable("DB_PORT")
DATABASE_DB = get_env_variable("DB_NAME")

SQLALCHEMY_DATABASE_URI = "%s://%s:%s@%s:%s/%s" % (
    DATABASE_DIALECT,
    DATABASE_USER,
    DATABASE_PASSWORD,
    DATABASE_HOST,
    DATABASE_PORT,
    DATABASE_DB,
)


#########################################
#       SETTING UP CELERY BROKER        #
#########################################
REDIS_HOST = get_env_variable("REDIS_HOST")
REDIS_PORT = get_env_variable("REDIS_PORT")


class CeleryConfig(object):
    broker_url = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
    imports = (
        "superset.sql_lab",
        "superset.tasks",
        "superset.tasks.thumbnails",
    )
    result_backend = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
    log_level = "DEBUG"
    worker_prefetch_multiplier = 10
    task_acks_late = True
    task_annotations = {
        "sql_lab.get_sql_results": {
            "rate_limit": "100/s",
        },
        "email_reports.send": {
            "rate_limit": "1/s",
            "time_limit": 600,
            "soft_time_limit": 600,
            "ignore_result": True,
        },
    }
    beat_schedule = {
        "reports.scheduler": {
            "task": "reports.scheduler",
            "schedule": crontab(minute="*", hour="*"),
        },
        "reports.prune_log": {
            "task": "reports.prune_log",
            "schedule": crontab(minute=10, hour=0),
        },
        "email_reports.schedule_hourly": {
            "task": "email_reports.schedule_hourly",
            "schedule": crontab(minute="1", hour="*"),
        },
        "cache-warmup-hourly": {
            "task": "cache-warmup",
            "schedule": crontab(minute="*/30", hour="*"),
            "kwargs": {
                "strategy_name": "top_n_dashboards",
                "top_n": 10,
                "since": "7 days ago",
            },
        },
    }


CELERY_CONFIG = CeleryConfig

###################################################
#       SCREENSHOT FOR ALERTS & REPORTS           #
###################################################
SCREENSHOT_LOCATE_WAIT = 100
SCREENSHOT_LOAD_WAIT = 600

# webdriver to take screenshots
WEBDRIVER_TYPE = "chrome"
WEBDRIVER_OPTION_ARGS = [
    "--force-device-scale-factor=2.0",
    "--high-dpi-support=2.0",
    "--headless",
    "--disable-gpu",
    "--disable-dev-shm-usage",
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-extensions",
]
WEBDRIVER_BASEURL = "http://superset:8088"
WEBDRIVER_BASEURL_USER_FRIENDLY = "http://localhost:8088"


#############################################
#       EMAIL REPORTS CONFIGURATION         #
#############################################
SMTP_HOST = get_env_variable("SMTP_HOST")
SMTP_STARTTLS = True
SMTP_SSL = False
SMTP_USER = get_env_variable("SMTP_USER")
SMTP_PORT = get_env_variable("SMTP_PORT")
SMTP_PASSWORD = get_env_variable("SMTP_PASSWORD")
SMTP_MAIL_FROM = get_env_variable("SMTP_MAIL_FROM")
```

_**Environment File**_
```bash
SECRET_KEY="XXXXXXXXXXXXXXXX"

# Runtime settings (don't change)
FLASK_ENV=production
SUPERSET_ENV=production
SUPERSET_PORT=8088

# Redis for caching
REDIS_HOST=redis
REDIS_PORT=6379

# Source database configuration (Shared RDS)
DB_DIALECT="postgresql"
DB_DRIVER="psycopg2"
DB_USER="postgres"
DB_PASSWORD="postgres"
DB_HOST="docker.for.mac.host.internal"
DB_PORT=5432
DB_NAME="XXXXXXX"

# Superset: Create admin user with following details
ADMIN_USERNAME="admin"
ADMIN_FIRST_NAME="Superset"
ADMIN_LAST_NAME="Admin"
ADMIN_EMAIL="superset-admin@superset.com"
ADMIN_PASSWORD="admin"

# SMTP configuration for email reports
SMTP_HOST="smtp.sendgrid.net"
SMTP_STARTTLS=True
SMTP_SSL=False
SMTP_USER="apikey"
SMTP_PORT=465
SMTP_PASSWORD="XXXXXXXXXXXXXXXX"
SMTP_MAIL_FROM="XXXXXXXXXXXXXXXX"
```

**_Dockerfile_**
```dockerfile
FROM apache/superset
# Switching to root to install the required packages
USER root

# Installing chrome driver for email & reports
RUN apt-get update
RUN apt-get -y install wget curl unzip

RUN apt-get update && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb && \
    rm -f google-chrome-stable_current_amd64.deb

RUN export CHROMEDRIVER_VERSION=$(curl --silent https://chromedriver.storage.googleapis.com/LATEST_RELEASE_102) && \
    wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip -d /usr/bin && \
    chmod 755 /usr/bin/chromedriver && \
    rm -f chromedriver_linux64.zip

# Installing the Postgres driver to connect to the metadata database
RUN pip install --no-cache psycopg2-binary psycopg2 redis gevent

# Add custom superset_config.py file and shell files
COPY config/superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py

COPY .env .
COPY all-roles.json .
COPY deploy/superset-custom.sh /app/superset-custom.sh
RUN chmod +x /app/superset-custom.sh

# Switching back to using the `superset` user
USER superset
ENTRYPOINT [ "/app/superset-custom.sh" ]
```

**_Docker compose_**
```yaml
version: "3.9"

services:
  redis:
    container_name: superset_cache
    image: redis:latest
    restart: on-failure
    volumes:
      - redis:/data

  worker:
    env_file: .env
    container_name: superset_worker
    image: superset-extended:latest
    command: ["celery", "--app=superset.tasks.celery_app:app", "worker", "--pool=gevent", "--concurrency=500"]
    user: "root"
    restart: on-failure
    healthcheck:
      disable: true
    depends_on:
      - redis
      - superset
    volumes:
      - ./config/:/app/pythonpath/

  beat:
    env_file: .env
    container_name: superset_worker_beat
    image: superset-extended:latest
    # command: ["/app/docker/docker-bootstrap.sh", "beat"]
    command: ["celery", "--app=superset.tasks.celery_app:app", "beat", "--pidfile", "/tmp/celerybeat.pid", "--schedule", "/tmp/celerybeat-schedule"]
    user: "root"
    restart: on-failure
    healthcheck:
      disable: true
    depends_on:
      - redis
      - superset
    volumes:
      - ./config/:/app/pythonpath/

  superset:
    env_file: .env
    container_name: superset_app
    image: superset-extended:latest
    # command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    command: ["gunicorn", "superset.app:create_app()", "--bind=0.0.0.0:8088", "--workers=5", "--worker-class=gthread", "--threads=4", "--timeout=200", "--limit-request-line=4094", "--limit-request-field_size=8190"]
    user: "root"
    restart: on-failure
    ports:
      - 8088:8088
    depends_on:
      - redis
    volumes:
      - ./config/:/app/pythonpath/

volumes:
  redis:
    external: false
```

I then created a report to be sent out every few minutes 
![Screenshot 2023-01-11 at 3 56 20 PM](https://user-images.githubusercontent.com/26377913/211784094-8872c266-250c-49a3-87d0-458eb1a7c285.png)

However, no reports are being sent or received.

**_I checked the logs for celery beat & celery worker - both the container logs are empty & do not contain any information regarding sending emails._**

Surprisingly, the REDIS is also empty - this raises the question of whether the task of sending emails is even being scheduled & stored in the message broker.

I have spent about 2-3 days on it & can't seem to find a way out. Kindly, let me know if there's anything that I am missing!

Any help would be greatly appreciated. Thanks!
