### DISCUSSION TITLE
Use superset user instead of root inside docker environment

### DISCUSSION THREAD

**Discussion by sebastianliebscher** [apache/superset#23578] [General]
According to the [Docker documentation](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user), a non-root user should be used if possible. The [docker-compose-non-dev.yml](https://github.com/apache/superset/blob/master/docker-compose-non-dev.yml) overrides the user to use _root_ instead of _superset_. The only reason I found is [being able to install packages from requirements-local.txt](https://github.com/apache/superset/pull/13926).

However, the requirements-local.txt is also installed without root for the superset user:

docker-compose-non-dev.yml
```
  superset:
    ...
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    # user: "root"
    restart: unless-stopped
    ...
```

docker-compose log:
```sh
Defaulting to user installation because normal site-packages is not writeable
Collecting nh3
  Downloading nh3-0.2.9-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 7.3 MB/s eta 0:00:00
Installing collected packages: nh3
Successfully installed nh3-0.2.9
````

I have not found any other errors so far when _root_ is changed to _superset_. Are there other reasons why ```user: "root"``` is used in `docker-compose-non-dev.yml`?
