### DISCUSSION TITLE
[feature] Enable environment variables in datasources yaml import

### DISCUSSION THREAD

**Discussion by sebastianliebscher** [apache/superset#23946] [Ideas]
The existing [feature to import datasources](https://superset.apache.org/docs/miscellaneous/importing-exporting-datasources#importing-datasources-from-yaml) with yaml configs is great but requires to hardcode credentials. This could be improved by parsing environment variables.

Before:

```yml
database_name: PostgreSQL Example
sqlalchemy_uri: postgresql://postgres:XXXXXXXXXX@172.17.0.1:5432/postgres
uuid: 6d3ce649-7288-4f82-8f31-fb06429b42ff
version: 1.0.0
```

After:
```yml
database_name: PostgreSQL Example
sqlalchemy_uri: !ENV 'postgresql://${PG_USER}:${PG_PASS}@172.17.0.1:5432/postgres'
uuid: 6d3ce649-7288-4f82-8f31-fb06429b42ff
version: 1.0.0
```

---

I think the change should be easy and something like:

```py
from pyaml_env import parse_config
contents[path_.name] = parse_config(str(path_))
```

instead of 

```py
with open(path_) as file:
    contents[path_.name] = file.read()
config = yaml.safe_load(content)
```

---

I identified these as relevant:
- https://github.com/apache/superset/blob/master/superset/cli/importexport.py#L378
- https://github.com/apache/superset/blob/master/superset/datasets/commands/importers/v0.py#L230
- https://github.com/apache/superset/tree/master/superset/datasets/commands/importers/v1

Tests:
- https://github.com/apache/superset/blob/master/tests/integration_tests/cli_tests.py#L308

But I don't understand the difference between v0 and v1 and the use of dispatcher to get started contributing myself. In test_cli.py both get tested:

```py
@mock.patch("superset.datasets.commands.importers.dispatcher.ImportDatasetsCommand")
def test_import_datasets_versioned_export(import_datasets_command, app_context, fs):
```

```py
@mock.patch("superset.datasets.commands.importers.v0.ImportDatasetsCommand")
def test_import_datasets_sync_argument_columns_metrics(import_datasets_command, app_context, fs):
```
