### DISCUSSION TITLE
How can SQLite can be used for metastore?

### DISCUSSION THREAD

**Discussion by cmontemuino** [apache/superset#25255] [General]
The documentation about Superset's metastore states SQLite comes out-of-the-box (see https://superset.apache.org/docs/installation/configuring-superset#using-a-production-metastore), although it's not recommended.

Only documentation I've found was removed in https://github.com/apache/superset/pull/23794

Dockerfile for development is using PostgreSQL, and `values.yaml` (from `helm/superset`) is clearly expecting a postgresql (https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L249-L259):

```yaml
  connections:
    # -- Change in case of bringing your own redis and then also set redis.enabled:false
    redis_host: '{{ .Release.Name }}-redis-headless'
    # redis_password: superset
    redis_port: "6379"
    # You need to change below configuration incase bringing own PostgresSQL instance and also set postgresql.enabled:false
    db_host: '{{ .Release.Name }}-postgresql'
    db_port: "5432"
    db_user: superset
    db_pass: superset
    db_name: superset
```

So I wonder if SQLite is really supported as metastore.
