### DISCUSSION TITLE
Superset behind reverse proxy (Caddy)

### DISCUSSION THREAD

**Discussion by T0573** [apache/superset#25500] [Q&A / Help]
Hey,

I'm trying to run Superset behind a reverse proxy and encountering some issues. I'm primarily using Caddy as my reverse proxy. If anyone has a similar setup and could share their configuration, it would be much appreciated. Configurations from other reverse proxies are also welcome.

Setup Details:

Superset is run via Docker Compose.

Configuration in superset_config_docker.py:

```
ENABLE_PROXY_FIX = True
PROXY_FIX_CONFIG = {"x_for": 1, "x_proto": 1, "x_host": 1, "x_port": 0, "x_prefix": 1}

```

docker-compose-non-dev.yml:
```
x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:2.1.1
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

version: "3.7"
services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - caddy_network

  db:
    env_file: docker/.env-non-dev
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - caddy_network

  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    networks:
      - caddy_network

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env-non-dev
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks:
      - caddy_network

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]
    networks:
      - caddy_network

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env-non-dev
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
    
volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
```

Caddyfile:                               
```
internal.xxx.com {
        log {
                output stdout
                level INFO
        }
        tls {
                dns godaddy x:y
        }

        route /superset* {
                reverse_proxy superset_app:8088 {
                        header_up X-Forwarded-For {remote}
                        header_up X-Forwarded-Proto {scheme}
                        header_up X-Forwarded-Host {host}
                        header_up X-Forwarded-Port {server_port}
                }
        }
}
```

docker logs superset_app:
```
2023-10-03 09:16:22,143:WARNING:superset.views.base:HTTPException
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1493, in dispatch_request
    self.raise_routing_exception(req)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1475, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 397, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/werkzeug/routing.py", line 2047, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
193.91.118.xxx:60398 - - [03/Oct/2023:09:16:22 +0000] "GET /superset HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
```

docker logs caddy:
```
2023-10-03T09:20:42.245810486Z {"level":"error","ts":1696324842.2455213,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"193.91.118.xxx","remote_port":"61158","client_ip":"193.91.118.xxx","proto":"HTTP/2.0","method":"GET","host":"internal.xxx.com","uri":"/superset","headers":{"Cookie":[],"If-None-Match":["\"1693342410.0-1947-4206103870\""],"If-Modified-Since":["Tue, 29 Aug 2023 20:53:30 GMT"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"],"Accept-Language":["en-GB,en;q=0.9"],"Accept-Encoding":["gzip, deflate, br"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"internal.xxx.com"}},"bytes_read":0,"user_id":"","duration":0.004345948,"size":1947,"status":404,"resp_headers":{"Last-Modified":["Tue, 29 Aug 2023 20:53:30 GMT"],"Server":["Caddy","gunicorn"],"Alt-Svc":["h3=\":443\"; ma=2592000"],"Etag":["\"1693342410.0-1947-4206103870\""],"Date":["Tue, 03 Oct 2023 09:20:42 GMT"],"Content-Length":["1947"],"Vary":["Accept-Encoding"],"Content-Disposition":["inline; filename=404.html"],"Content-Type":["text/html; charset=utf-8"],"Cache-Control":["no-cache, max-age=0"],"Expires":["Tue, 03 Oct 2023 09:20:42 GMT"]}}
2023-10-03T09:20:42.314048170Z {"level":"info","ts":1696324842.3138235,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"193.91.118.xxx","remote_port":"61158","client_ip":"193.91.118.xxx","proto":"HTTP/2.0","method":"GET","host":"internal.xxx.com","uri":"/static/assets/1a1474519a0ea853fdce.png","headers":{"Accept-Language":["en-GB,en;q=0.9"],"Referer":["https://internal.xxx.com/superset"],"Cookie":[],"Accept":["image/webp,image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"internal.xxx.com"}},"bytes_read":0,"user_id":"","duration":0.00001556,"size":0,"status":0,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3=\":443\"; ma=2592000"]}}
```
