### DISCUSSION TITLE
SELECT is not allowed in cluster mode

### DISCUSSION THREAD

**Discussion by AHulshoff** [apache/superset#27713] [Q&A / Help]
I tried to install Superset on kubernetes with the helm chart. As I already had a redis and postgres environment, I decided to reuse them. So I configured values.yml to use the correct parameters to setup the environments. But after deploying the helm chart, I found out that Superset is not working properly. After some investigation I found out that Superset worker is trying to start, but fails a little after with the following error message:

> [2024-03-26 17:11:13,020: ERROR/MainProcess] consumer: Cannot connect to redis://:**@redis-redis-cluster-headless.redis.svc.cluster.local:6379/2: SELECT is not allowed in cluster mode.
> Trying again in 6.00 seconds... (3/100)

On Slack, I asked a similar question where someone thought it might be caused by the redis client not be configured to use a redis cluster. I have done some research and he might be right. If I look at the code of Superset, I cannot find a reference to redis cluster. Unfortunately, I am not an expert on using redis in python... Or redis in general for that matter. In other investigations I have done, I couldn't find any references to a similar problem. So I am not sure it is a bug and therefore I assume I made a mistake somewhere.
Both redis and postgres clusters are also running on kubernetes and are installed with the Bitnami helm charts.

My values.yml:
```yaml
service:
  type: LoadBalancer
  port: 8088
  nodePort:
    http: 30111
supersetNode:
  connections:
    redis_host: redis-redis-cluster-headless.redis.svc.cluster.local
    redis_port: 6379
    redis_password: [redacted]
    redis_cache_db: 1
    redis_celery_db: 2
    db_host: [redacted]
    db_port: 5432
    db_user: [redacted]
    db_pass: [redacted]
    db_name: superset
postgresql:
  enabled: false
redis:
  enabled: false
configOverrides:
  secret: |
    SECRET_KEY = [redacted]
    CACHE_KEY_PREFIX = 'superset_'
```
Can someone help me to solve this?
