### DISCUSSION TITLE
Get rid of custom IDs and use UUIDs instead

### DISCUSSION THREAD

**Discussion by ozichert** [apache/superset#28552] [Ideas]
Hello together,

we are very happy to use Superset within our company but we do have some issues with the Superset generated IDs for charts, dashboards, data sets and filters that are mapped within the database (see e.g. table `dashboard_slices`). Each of these components do also have a UUID that can be used instead. When exporting and importing the dashboard to another Superset source, this newly generated IDs do change, whereas the UUIDs stay the same. This makes importing and exporting difficult to handle.

To make the problem clearer, i want to share a `.yaml` file for some chart.
```
slice_name: Customers
description: Shows the number of customers that have been online per week.
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 145__table
  viz_type: echarts_area
  slice_id: 5
  cache_timeout: 300
  x_axis: starttime
  time_grain_sqla: P1W
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      [...]
query_context: null
cache_timeout: 300
uuid: d21389ab-0057-4091-8cc6-c1ffd5c5b5db
version: 1.0.0
dataset_uuid: 0138d785-3210-4caf-868f-10a45f823e93
```
In this case we have newly generated IDs `slice_id` and `datasource` within the params key, that are also used in the database tables. These should be removed and the UUIDs (`uuid` and `dataset_uuid`) can be used.

Therefore the idea is to get rid of these IDs in the `.yaml` files as well as in the database tables and replace them with the UUID (if not already part of the content). My assumption is that these Superset generated IDs are not required anymore and the UUIDs were introduced in a later stage with growth of the project. Am I right with this assumption or is there any requirement to keep these IDs?

Best regards and thank you in advance for responding
