### DISCUSSION TITLE
Zero downtime application deployment

### DISCUSSION THREAD

**Discussion by Step1N** [apache/superset#29500] [General]
Hi,

I am trying deploy superset with zero downtime. For this exploring possibility using blue/green deployment strategy. Whether i can achieve it or not.   

                                     [ELB]

       [Application Cluster]Blue                    [Application Cluster] Green

                          [application db] shared         
                          [application cache] shared

Any help appreciated.

Thanks

**Comment by dosubot** [comment]
Hey @Step1N,

I'm here to assist you with any bugs, questions, or contributions you might have. Let me know how I can help!

Cheers!


To deploy Superset with zero downtime using a blue/green deployment strategy with an Elastic Load Balancer (ELB) and two application clusters that share the same application database and cache, you can follow these steps:

1. **Create Two Separate Deployments**: Create two separate deployments for the blue and green environments. Each deployment will have its own set of pods but will share the same database and cache.

2. **Configure the ELB**: Configure the ELB to route traffic to the blue deployment initially.

3. **Deploy the Green Environment**: Deploy the green environment with the new version of Superset.

4. **Switch Traffic to the Green Environment**: Update the ELB to route traffic to the green deployment.

5. **Monitor and Rollback if Necessary**: Monitor the green deployment for any issues. If there are issues, you can switch the traffic back to the blue deployment.

Here is an example of how you can configure the Helm chart for the blue and green deployments:

### Blue Deployment (`values-blue.yaml`)
```yaml
supersetNode:
  replicas:
    replicaCount: 3
  deploymentLabels:
    environment: blue
  podLabels:
    environment: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  env:
    - name: SUPERSET_ENV
      value: "blue"
```

### Green Deployment (`values-green.yaml`)
```yaml
supersetNode:
  replicas:
    replicaCount: 3
  deploymentLabels:
    environment: green
  podLabels:
    environment: green
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  env:
    - name: SUPERSET_ENV
      value: "green"
```

### Deploy Blue Environment
```sh
helm upgrade --install superset-blue -f values-blue.yaml superset
```

### Deploy Green Environment
```sh
helm upgrade --install superset-green -f values-green.yaml superset
```

### Update ELB to Route Traffic to Green Deployment
Update the ELB configuration to route traffic to the green deployment. This can be done through the AWS Management Console or using the AWS CLI.

### Monitor and Rollback if Necessary
Monitor the green deployment. If there are any issues, you can update the ELB to route traffic back to the blue deployment.

Additionally, ensure that your `superset_config.py` is properly configured and accessible by both deployments. You can set the `SUPERSET_CONFIG_PATH` environment variable to point to your configuration file:

```bash
export SUPERSET_CONFIG_PATH=/app/superset_config.py
```

If you are using Docker, you can copy the configuration file into the container and set the environment variable:

```bash
COPY --chown=superset superset_config.py /app/
ENV SUPERSET_CONFIG_PATH /app/superset_config.py
```

By following these steps, you can achieve zero downtime deployment using a blue/green deployment strategy with an Elastic Load Balancer and two application clusters that share the same application database and cache <sup>[[1]](https://github.com/apache/superset/blob/master/helm/superset/templates/deployment.yaml)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/docs/docs/configuration/configuring-superset.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
