### DISCUSSION TITLE
legend order for mixed charts.

### DISCUSSION THREAD

**Discussion by sunilreddy0720** [apache/superset#29773] [General]
Guys,

suppose i have a Time series mixed chart.

and my legend order is
![image](https://github.com/user-attachments/assets/e53ecbca-88af-4140-a424-1ca45bf01804)

i want my legend order to be Year1 year2 year3 year4+ Rolling 4 week average.

is there any option that can we alert this legend order ?

how to achieve this?
Here is the JSON metadata you need to add to set the legend order to "Year 1", "Year 2", "Year 3", "Year 4+", and "Rolling 4 week average":

{
  "legend_order": ["Year 1", "Year 2", "Year 3", "Year 4+", "Rolling 4 week average"]
}

is there any alternative to do it from frontend but no codebase change?

**Comment by dosubot** [comment]
To achieve the desired legend order for your mixed chart, you can use the `sort_series_type` and `sort_series_ascending` controls in the Superset UI. Unfortunately, there is no direct way to set a custom legend order through the JSON metadata without making changes to the codebase.

Here is how you can configure the sorting options in the Superset UI:

1. **Sort Series By**: This control allows you to specify the criteria for sorting the series.
2. **Sort Series Ascending**: This control allows you to specify whether the series should be sorted in ascending order.

Here is the relevant code snippet for these controls:

```tsx
const sortSeriesType: ControlSetItem = {
  name: 'sort_series_type',
  config: {
    type: 'SelectControl',
    freeForm: false,
    label: t('Sort Series By'),
    choices: SORT_SERIES_CHOICES,
    default: DEFAULT_SORT_SERIES_DATA.sort_series_type,
    renderTrigger: true,
    description: t('Based on what should series be ordered on the chart and legend'),
  },
};

const sortSeriesAscending: ControlSetItem = {
  name: 'sort_series_ascending',
  config: {
    type: 'CheckboxControl',
    label: t('Sort Series Ascending'),
    default: DEFAULT_SORT_SERIES_DATA.sort_series_ascending,
    renderTrigger: true,
    description: t('Sort series in ascending order'),
  },
};

export const seriesOrderSection: ControlSetRow[] = [
  [<ControlSubSectionHeader>{t('Series Order')}</ControlSubSectionHeader>],
  [sortSeriesType],
  [sortSeriesAscending],
];
```

These controls allow you to dynamically alter the legend order through the frontend without modifying the core codebase <sup>[[1]](https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-echarts/src/controls.tsx)</sup>.

If you need to implement a custom legend order, you would need to modify the `sortAndFilterSeries` function to accept a custom order parameter and use it to sort the series names accordingly. Here is an example of how you can modify the function:

```ts
export function sortAndFilterSeries(
  rows: DataRecord[],
  xAxis: string,
  extraMetricLabels: any[],
  sortSeriesType?: SortSeriesType,
  sortSeriesAscending?: boolean,
  customOrder?: string[], // Add this parameter to accept custom order
): string[] {
  const seriesNames = Object.keys(rows[0])
    .filter(key => key !== xAxis)
    .filter(key => !extraMetricLabels.includes(key));

  let aggregator: (name: string) => { name: string; value: any };

  switch (sortSeriesType) {
    case SortSeriesType.Sum:
      aggregator = name => ({ name, value: sumBy(rows, name) });
      break;
    case SortSeriesType.Min:
      aggregator = name => ({ name, value: minBy(rows, name)?.[name] });
      break;
    case SortSeriesType.Max:
      aggregator = name => ({ name, value: maxBy(rows, name)?.[name] });
      break;
    case SortSeriesType.Avg:
      aggregator = name => ({ name, value: meanBy(rows, name) });
      break;
    default:
      aggregator = name => ({ name, value: name.toLowerCase() });
      break;
  }

  const sortedValues = seriesNames.map(aggregator);

  let sortedSeries = orderBy(
    sortedValues,
    ['value'],
    [sortSeriesAscending ? 'asc' : 'desc'],
  ).map(({ name }) => name);

  // Apply custom order if provided
  if (customOrder && customOrder.length > 0) {
    sortedSeries = customOrder.filter(name => sortedSeries.includes(name));
  }

  return sortedSeries;
}
```

This modification allows you to pass a custom order for the legend items directly in the chart's configuration <sup>[[2]](https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-echarts/src/utils/series.ts)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by sunilreddy0720** [reply]
Hi 
i want to achieve this from frontend not required any code change

**Reply by dosubot** [reply]
To achieve custom legend ordering from the frontend without modifying the codebase, you can use the existing controls in the Superset UI. Specifically, the `sort_series_type` and `sort_series_ascending` controls can help you define the order of series on the chart and legend.

Here are the steps:

1. **Sort Series By**: This control allows you to specify the criteria for sorting the series.
2. **Sort Series Ascending**: This control allows you to specify whether the series should be sorted in ascending order.

Here is the relevant code snippet for these controls:

```tsx
const sortSeriesType: ControlSetItem = {
  name: 'sort_series_type',
  config: {
    type: 'SelectControl',
    freeForm: false,
    label: t('Sort Series By'),
    choices: SORT_SERIES_CHOICES,
    default: DEFAULT_SORT_SERIES_DATA.sort_series_type,
    renderTrigger: true,
    description: t('Based on what should series be ordered on the chart and legend'),
  },
};

const sortSeriesAscending: ControlSetItem = {
  name: 'sort_series_ascending',
  config: {
    type: 'CheckboxControl',
    label: t('Sort Series Ascending'),
    default: DEFAULT_SORT_SERIES_DATA.sort_series_ascending,
    renderTrigger: true,
    description: t('Sort series in ascending order'),
  },
};

export const seriesOrderSection: ControlSetRow[] = [
  [<ControlSubSectionHeader>{t('Series Order')}</ControlSubSectionHeader>],
  [sortSeriesType],
  [sortSeriesAscending],
];
```

These controls allow you to dynamically alter the legend order through the frontend without modifying the core codebase <sup>[[1]](https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-echarts/src/controls.tsx)</sup>.

If you need a specific custom order like "Year 1", "Year 2", "Year 3", "Year 4+", and "Rolling 4 week average", you might need to manually adjust the sorting criteria to match your desired order using these controls. However, for a fully custom order, a code change would typically be required.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by sunilreddy0720** [comment]
i want achieve this for specific chart using json metadata

**Reply by dosubot** [reply]
To achieve a custom legend order for a specific time series mixed chart using JSON metadata, you can modify the `params` section of the YAML configuration to include the `legendOrder` parameter. Here is an example of how you can do it:

```yaml
slice_name: Mixed
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 22__table
  viz_type: mixed_timeseries
  x_axis: order_date
  time_grain_sqla: P1M
  metrics:
    - expressionType: SIMPLE
      column:
        advanced_data_type: null
        certification_details: null
        certified_by: null
        column_name: sales
        description: null
        expression: null
        filterable: true
        groupby: true
        id: 734
        is_certified: false
        is_dttm: false
        python_date_format: null
        type: DOUBLE PRECISION
        type_generic: 0
        verbose_name: null
        warning_markdown: null
      aggregate: SUM
      sqlExpression: null
      datasourceWarning: false
      hasCustomLabel: false
      label: SUM(sales)
      optionName: metric_b9hph4jr9i_nayy40sodwl
  groupby: []
  adhoc_filters:
    - clause: WHERE
      subject: order_date
      operator: TEMPORAL_RANGE
      comparator: No filter
      expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
    - count
  groupby_b: []
  adhoc_filters_b:
    - clause: WHERE
      subject: order_date
      operator: TEMPORAL_RANGE
      comparator: No filter
      expressionType: SIMPLE
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  markerSize: 6
  yAxisIndex: 1
  seriesTypeB: bar
  opacityB: 0.2
  markerSizeB: 6
  yAxisIndexB: 0
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendOrder: ['Year 1', 'Year 2', 'Year 3', 'Year 4+', 'Rolling 4 week average']  # Custom legend order
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  y_axis_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  y_axis_bounds_secondary:
    - null
    - null
  y_axis_format_secondary: SMART_NUMBER
  extra_form_data: {}
  dashboards: []
cache_timeout: null
uuid: bb394e7b-0cfc-47ba-b067-541964545752
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
```

In this example, the `legendOrder` parameter is added to the `params` section with the desired order of the legend items. Adjust the order of the items in the `legendOrder` list as needed <sup>[[1]](https://github.com/apache/superset/blob/master/superset/examples/configs/charts/Featured Charts/Mixed.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
