### DISCUSSION TITLE
创建charts时， 是否可以设置多个搜索框？

### DISCUSSION THREAD

**Discussion by weidongweidong** [apache/superset#29972] [Q&A / Help]
创建charts时， 是否可以设置多个搜索框？  目前来看只能在query - filters 中限定日期区间， 但是我想在搜索框动态的筛选日期， 这样可以么 ？

**Comment by dosubot** [comment]
Hey @weidongweidong! I'm here to help you with any bugs, questions, or contributions you have. Let me know how I can assist you!


是的，在创建charts时，可以设置多个搜索框，并在搜索框动态筛选日期。

在提供的YAML配置文件中，`adhoc_filters`部分显示了如何设置日期筛选条件。你可以添加多个`adhoc_filters`来实现多个搜索框，并使用`TEMPORAL_RANGE`操作符来动态筛选日期。

例如，以下是一个示例配置，展示了如何设置两个日期筛选框：

```yaml
adhoc_filters:
  - clause: WHERE
    subject: order_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  - clause: WHERE
    subject: another_date_field
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
```

通过这种方式，你可以在图表中添加多个日期筛选框，并动态筛选日期<sup>[[1]](https://github.com/apache/superset/blob/master/superset/examples/configs/charts/Featured Charts/Mixed.yaml)</sup>。

不过需要注意的是，当前实现中只有第一个`TEMPORAL_RANGE`筛选器会被使用，这意味着多个`TEMPORAL_RANGE`筛选器可能无法按预期工作<sup>[[2]](https://github.com/apache/superset/blob/master/superset-frontend/plugins/plugin-chart-echarts/src/BigNumber/BigNumberPeriodOverPeriod/transformProps.ts)</sup>。



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
