### DISCUSSION TITLE
Migrate system

### DISCUSSION THREAD

**Discussion by SquirHong** [apache/superset#29980] [Q&A / Help]
Hello everyone, my superset system is now deployed on aliyun machine, and now I want to migrate to aws cloud, may I ask how I can complete the migration? In addition to mirror migration, I would like to know whether superset system supports all data migration? I didn't find any description of the migration in the official documentation

**Comment by dosubot** [comment]
Hey @SquirHong! 👋 I'm here to help you with any questions or issues you have. I'm a bot that can help you solve bugs, answer questions, and become a contributor.


To migrate your Superset system from an Aliyun machine to AWS Cloud, you can follow these general steps:

1. **Backup Your Superset Metadata Database**: This includes all your dashboards, charts, and other configurations. You can use a tool like `pg_dump` for PostgreSQL or `mysqldump` for MySQL to create a backup of your metadata database.

2. **Transfer the Backup to AWS**: Use a secure method to transfer your backup file to your AWS environment. This could be done using `scp`, `rsync`, or uploading to an S3 bucket.

3. **Restore the Backup on AWS**: Set up a new database instance on AWS (RDS, for example) and restore the backup using the appropriate tool (`psql` for PostgreSQL, `mysql` for MySQL).

4. **Set Up Superset on AWS**: Follow the [installation guide](https://superset.apache.org/docs/installation/docker-compose) to set up Superset on your AWS environment. You can use Docker Compose or a Helm chart for Kubernetes.

5. **Configure Superset to Use the Restored Database**: Update your Superset configuration to point to the new database instance on AWS.

Regarding data migration, Superset itself does not handle the migration of the actual data from your data sources. Superset supports querying data from any SQL-speaking datastore or data engine that has a Python DB-API driver and a SQLAlchemy dialect. You will need to ensure that your data sources are accessible from your new AWS environment and update the database connection configurations in Superset accordingly.

**Supported Databases**:
Superset can query data from a wide range of databases, including but not limited to:
- PostgreSQL
- MySQL
- MariaDB
- SQLite
- Microsoft SQL Server
- Oracle
- Redshift
- Google BigQuery
- Snowflake
- Trino
- Presto
- Databricks
- Druid
- Firebolt
- Timescale
- Rockset
- IBM DB2
- Sybase
- Vertica
- Firebird
- Greenplum
- ClickHouse
- Exasol
- MonetDB
- Apache Kylin
- Hologres
- Netezza
- Pinot
- Teradata
- Yugabyte
- Databend
- StarRocks
- Doris
- OceanBase

For a more comprehensive list and configuration instructions, refer to the [Superset documentation](https://superset.apache.org/docs/configuration/databases).

```bash
# Example of backing up a PostgreSQL database
pg_dump -U your_username -h your_aliyun_host -d your_database > backup.sql

# Example of restoring a PostgreSQL database on AWS
psql -U your_username -h your_aws_host -d your_database < backup.sql
```

```yaml
# Example Docker Compose configuration for Superset
version: "3.1"
services:
  superset:
    image: apache/superset
    environment:
      - SUPERSET_DATABASE_URI=postgresql+psycopg2://your_username:your_password@your_aws_host/your_database
    ports:
      - "8088:8088"
    volumes:
      - ./superset_home:/app/superset_home
```

```yaml
# Example Helm values.yaml for Superset
superset:
  configOverrides:
    SUPERSET_DATABASE_URI: postgresql+psycopg2://your_username:your_password@your_aws_host/your_database
```

By following these steps, you can migrate your Superset system to AWS Cloud <sup>[[1]](https://github.com/apache/superset/blob/master/README.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
