### DISCUSSION TITLE
Superset Readiness\Liveness probe failed

### DISCUSSION THREAD

**Discussion by underdark456** [apache/superset#29992] [Q&A / Help]
Hello, superset's pods periodically restarts with 
```
3m38s       Warning   Unhealthy   pod/superset-f55c54686-k48cc   Readiness probe failed: Get "http://10.10.101.165:8088/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
46m         Warning   Unhealthy   pod/superset-f55c54686-k48cc   Liveness probe failed: Get "http://10.10.101.165:8088/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
46m         Normal    Killing     pod/superset-f55c54686-k48cc   Container superset failed liveness probe, will be restarted
```
Probe configured like that
```yaml
  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /health
      port: http
      scheme: HTTP
```
I noticed following in container logs:
```
2024-08-22 10:44:44,690:warning:urllib3.connectionpool:Connection pool is full, discarding connection: 10.100.2.102. Connection pool size: 8              │
│ superset 2024-08-22 10:44:44,959:warning:urllib3.connectionpool:Connection pool is full, discarding connection: 10.100.2.102. Connection pool size: 8              │
│ superset 2024-08-22 10:44:45,073:warning:urllib3.connectionpool:Connection pool is full, discarding connection: 10.100.2.102. Connection pool size: 8              │
│ superset 2024-08-22 10:44:47,498:warning:urllib3.connectionpool:Connection pool is full, discarding connection: 10.100.2.102. Connection pool size: 8
```
Could this have something to do with the problem and if so, how to solve it?

**Comment by dosubot** [comment]
Hey there, @underdark456! I'm here to help you out with any issues you're facing. I can assist with bug fixes, answer your questions, and guide you on becoming a contributor. Let's tackle this together!


Yes, the "Connection pool is full" warnings in the Superset container logs could be causing the readiness and liveness probe failures. This issue can be resolved by increasing the connection pool size or optimizing the usage of connections.

To address this, you can adjust the Gunicorn settings in the `values.yaml` file to increase the number of workers and threads, which can help manage the load better and prevent the connection pool from getting full.

Here is an example of how you can configure these settings:

```yaml
extraEnv:
  # Increase the gunicorn worker amount, can improve performance drastically
  # See: https://docs.gunicorn.org/en/stable/design.html#how-many-workers
  SERVER_WORKER_AMOUNT: 4
  # Increase the number of threads per worker
  SERVER_THREADS_AMOUNT: 20
  # Extend timeout to allow long running queries.
  GUNICORN_TIMEOUT: 300
  # Set the maximum number of requests a worker will process before restarting
  WORKER_MAX_REQUESTS: 1000
  # Add some jitter to the max requests to avoid all workers restarting at the same time
  WORKER_MAX_REQUESTS_JITTER: 50
```

These settings will help manage the load more effectively and reduce the likelihood of the connection pool getting full, which should help with the readiness and liveness probe failures <sup>[[1]](https://github.com/apache/superset/blob/master/helm/superset/values.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
