### DISCUSSION TITLE
How to make thumbnails visible to all users

### DISCUSSION THREAD

**Discussion by Atli-Nordmann** [apache/superset#30014] [Q&A / Help]
Hello.

I have searched quite a bit online but I have not found a way to accomplish this.
I have Apache Superset as a BI tool for my organization. Therefore, many people use it without having a specific user.
I want to configure Superset such that anyone can view thumbnails for dashboards without having to log in.
How can I accomplish this?

apache-superset: 4.0.1
python: 3.9.18

**Comment by dosubot** [comment]
Hello @Atli-Nordmann 👋, I'm here to assist you with any issues or questions you have regarding the repository. Let's get started!


To configure Apache Superset 4.0.1 to allow anyone to view thumbnails for dashboards without having to log in, you need to set the `AUTH_ROLE_PUBLIC` and `PUBLIC_ROLE_LIKE` configurations in the `superset/config.py` file. Additionally, ensure that the `THUMBNAILS` feature is enabled. Here is how you can do it:

1. Set the `AUTH_ROLE_PUBLIC` to `'Public'`.
2. Set the `PUBLIC_ROLE_LIKE` to `'Gamma'` or another role that has the necessary permissions to view dashboards.
3. Ensure that the `THUMBNAILS` feature is enabled.

Here is the relevant configuration:

```py
# Uncomment to setup Public role name, no authentication needed
AUTH_ROLE_PUBLIC = 'Public'

# Grant public role the same set of permissions as for a selected builtin role.
# This is useful if one wants to enable anonymous users to view
# dashboards. Explicit grant on specific datasets is still required.
PUBLIC_ROLE_LIKE = 'Gamma'

# Enable the thumbnails feature
FEATURE_FLAGS = {
    "THUMBNAILS": True,
}

# Additional configuration for thumbnail caching
THUMBNAIL_CACHE_CONFIG = {
    "CACHE_TYPE": "RedisCache",
    "CACHE_DEFAULT_TIMEOUT": 10000,
    "CACHE_KEY_PREFIX": "superset_thumbnails_",
    "CACHE_REDIS_HOST": "localhost",  # Replace with your Redis host
    "CACHE_REDIS_PORT": 6379,         # Replace with your Redis port
    "CACHE_REDIS_DB": 2,              # Replace with your Redis DB
}
```

This configuration will allow anonymous users to view thumbnails for dashboards without needing to log in. Make sure to adjust the Redis configuration according to your environment <sup>[[1]](https://github.com/apache/superset/blob/master/superset/config.py)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/superset/dashboards/api.py)</sup><sup>[[3]](https://github.com/apache/superset/blob/master/tests/integration_tests/superset_test_config_thumbnails.py)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by Atli-Nordmann** [comment]
@dosu

I have made the changes you suggested but thumbnails are still not visible to anonymous user.
Could you be more specific about the changes needed in the Redis configuration?

**Reply by dosubot** [reply]
To make thumbnails visible to anonymous users in Apache Superset, ensure the following Redis configuration and other settings are correctly applied:

1. **Redis Configuration for Thumbnail Caching**:
   Ensure that the `THUMBNAIL_CACHE_CONFIG` is set to use `RedisCache` and points to the correct Redis host and port. Here is the configuration snippet:

   ```python
   THUMBNAIL_CACHE_CONFIG = {
       "CACHE_TYPE": "RedisCache",
       "CACHE_DEFAULT_TIMEOUT": 10000,
       "CACHE_KEY_PREFIX": "superset_thumbnails_",
       "CACHE_REDIS_URL": "redis://localhost:6379/0"  # Adjust the URL as needed
   }
   ```

2. **Public Role Configuration**:
   Set the `PUBLIC_ROLE_LIKE` and `AUTH_ROLE_PUBLIC` configurations to allow public access:

   ```python
   PUBLIC_ROLE_LIKE = "Gamma"
   AUTH_ROLE_PUBLIC = "Public"
   ```

3. **Enable Thumbnails Feature**:
   Ensure that the `THUMBNAILS` feature flag is enabled:

   ```python
   FEATURE_FLAGS = {
       "THUMBNAILS": True,
       "THUMBNAILS_SQLA_LISTENERS": True,
   }
   ```

4. **Execute Thumbnails as Selenium User**:
   To ensure that thumbnails execute as the selenium user for anonymous users, add the following to your `superset_config.py`:

   ```python
   from superset.tasks.types import ExecutorType

   THUMBNAIL_SELENIUM_USER = "admin"
   THUMBNAIL_EXECUTE_AS = [ExecutorType.SELENIUM]
   ```

These settings should ensure that thumbnails are cached in Redis and are accessible to anonymous users <sup>[[1]](https://github.com/apache/superset/blob/master/tests/integration_tests/superset_test_config_thumbnails.py)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/superset/config.py)</sup><sup>[[3]](https://github.com/apache/superset/blob/master/UPDATING.md)</sup><sup>[[4]](https://github.com/apache/superset/blob/master/docs/docs/configuration/cache.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by Atli-Nordmann** [comment]
@dosu

Thank you. That worked.
One more question. 
Is the celery beat necessary if I only need to cache thumbnails and dashboards?

**Reply by dosubot** [reply]
Yes, the Celery beat is necessary if you need to cache thumbnails and dashboards in Apache Superset. For caching thumbnails, you will need a cache system and Celery workers. Thumbnails are processed asynchronously by the workers, which implies the necessity of Celery.

Supporting evidence from the documentation:
> For this feature you will need a cache system and celery workers. All thumbnails are stored on cache and are processed asynchronously by the workers <sup>[[1]](https://github.com/apache/superset/blob/master/docs/docs/configuration/cache.mdx)</sup>.

Additionally, the configuration file `superset/config.py` includes Celery settings, indicating its integral role in task scheduling and execution:
```python
class CeleryConfig:  # pylint: disable=too-few-public-methods
    broker_url = "sqla+sqlite:///celerydb.sqlite"
    imports = (
        "superset.sql_lab",
        "superset.tasks.scheduler",
        "superset.tasks.thumbnails",
        "superset.tasks.cache",
    )
    result_backend = "db+sqlite:///celery_results.sqlite"
    worker_prefetch_multiplier = 1
    task_acks_late = False
    task_annotations = {
        "sql_lab.get_sql_results": {
            "rate_limit": "100/s",
        },
    }
    beat_schedule = {
        "reports.scheduler": {
            "task": "reports.scheduler",
            "schedule": crontab(minute="*", hour="*"),
            "options": {"expires": int(CELERY_BEAT_SCHEDULER_EXPIRES.total_seconds())},
        },
        "reports.prune_log": {
            "task": "reports.prune_log",
            "schedule": crontab(minute=0, hour=0),
        },
    }
}
``` <sup>[[2]](https://github.com/apache/superset/blob/master/superset/config.py)</sup>.


<!-- Dosu Comment Footer -->
*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by Atli-Nordmann** [comment]
@dosu

Are you sure?
In the documentation it only says:
"To start a job which schedules periodic background jobs, run the following command:"
"celery --app=superset.tasks.celery_app:app beat"

**Reply by dosubot** [reply]
Celery beat is not necessary for caching thumbnails and dashboards in Apache Superset. Celery beat is only required for scheduling periodic background jobs, such as alerts and reports.

The caching tasks (`cache_chart_thumbnail`, `cache_dashboard_thumbnail`, and `cache_dashboard_screenshot`) are defined as Celery tasks and can be executed by a Celery worker without the need for Celery beat. These tasks can be triggered manually or by other parts of the application.

Here is the relevant code snippet:

```python
@celery_app.task(name="cache_chart_thumbnail", soft_time_limit=300)
def cache_chart_thumbnail(
    current_user: Optional[str],
    chart_id: int,
    force: bool = False,
    window_size: Optional[WindowSize] = None,
    thumb_size: Optional[WindowSize] = None,
) -> None:
    # Task implementation
    ...

@celery_app.task(name="cache_dashboard_thumbnail", soft_time_limit=300)
def cache_dashboard_thumbnail(
    current_user: Optional[str],
    dashboard_id: int,
    force: bool = False,
    thumb_size: Optional[WindowSize] = None,
    window_size: Optional[WindowSize] = None,
) -> None:
    # Task implementation
    ...

@celery_app.task(name="cache_dashboard_screenshot", soft_time_limit=300)
def cache_dashboard_screenshot(
    current_user: Optional[str],
    dashboard_id: int,
    dashboard_url: str,
    force: bool = True,
    thumb_size: Optional[WindowSize] = None,
    window_size: Optional[WindowSize] = None,
) -> None:
    # Task implementation
    ...
```

Additionally, the `helm/superset/values.yaml` file specifies that Celery beat is required only if you intend to use alerts and reports:

```yaml
# Superset beat configuration (to trigger scheduled jobs like reports)
supersetCeleryBeat:
  # -- This is only required if you intend to use alerts and reports
  enabled: false
  # -- Sets the [pod disruption budget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) for supersetCeleryBeat pods
  podDisruptionBudget:
    # -- Whether the pod disruption budget should be created
    enabled: false
    # -- If set, maxUnavailable must not be set - see https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
    minAvailable: 1
    # -- If set, minAvailable must not be set - see https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
    maxUnavailable: 1
  # -- Command
  # @default -- a `celery beat` command
  command:
    - "/bin/sh"
    - "-c"
    - ". {{ .Values.configMountPath }}/superset_bootstrap.sh; celery --app=superset.tasks.celery_app:app beat --pidfile /tmp/celerybeat.pid --schedule /tmp/celerybeat-schedule"
  # -- If true, forces deployment to reload on each upgrade
  forceReload: false
  # -- List of init containers
  # @default -- a container waiting for postgres
  initContainers:
    - name: wait-for-postgres-redis
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: "{{ .Values.initImage.pullPolicy }}"
      envFrom:
        - secretRef:
            name: "{{ tpl .Values.envFromSecret . }}"
      command:
        - /bin/sh
        - -c
        - dockerize -wait "tcp://$DB_HOST:$DB_PORT" -wait "tcp://$REDIS_HOST:$REDIS_PORT" -timeout 120s
  # -- Launch additional containers into supersetCeleryBeat pods
  extraContainers: []
  # -- Annotations to be added to supersetCeleryBeat deployment
  deploymentAnnotations: {}
  # -- Affinity to be added to supersetCeleryBeat deployment
  affinity: {}
  # -- TopologySpreadConstrains to be added to supersetCeleryBeat deployments
  topologySpreadConstraints: []
  # -- Annotations to be added to supersetCeleryBeat pods
```

Therefore, while Celery workers are necessary for processing these tasks, Celery beat is not required unless you need to schedule periodic background jobs like alerts and reports <sup>[[1]](https://github.com/apache/superset/blob/master/superset/tasks/thumbnails.py)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/helm/superset/values.yaml)</sup><sup>[[3]](https://github.com/apache/superset/blob/master/docs/docs/configuration/cache.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
