### DISCUSSION TITLE
Disable JsonDownload and copy to clipboard

### DISCUSSION THREAD

**Discussion by SaJu84** [apache/superset#30161] [Q&A / Help]
Hello,
For our local superset instance(version 4.0.2) we created a new role with its special permission that should be able to see the charts but should not be able to download the data. The role inherits from the alpha role but via a custom security manager we took some permissions away.  Here are our forbidden pvms:     FORBIDDEN_PVM = {
        ("menu_access", "SQL Lab"),
        ("menu_access", "SQL Editor"),
        ("menu_access", "Saved Queries"),
        ("menu_access", "Query Search"),
        ("can_csv", "Superset"),
        ("can_export", "ImportExportRestApi"),
        ("can_export", "Dashboard"),
        ("can_export", "Dataset"),
        ("can_export", "Chart"),
        ("can_view_chart_as_table", "Dashboard"),
    } 
I also double-checked it via admin access and our role really doesn't have these forbissen permissions.
When I login with this role, open a chat and go to the download menu it looks like this: 
![Download-options](https://github.com/user-attachments/assets/0724fe91-f641-4f92-8c65-d3e262fe5873)
So only export to .CSV is disable. The excel export delivers the following: {"message":"Forbidden"}, so this is also fine with me. Burt via Export to .JSON, I can download all the charts data. Is there any permission I am missing? I checked the code and to me it looked like taking away the 'can csv on Superset' should be enough. 
It is also possible to download the data from the RESULT tab via the copy to clipboard button. Is there a possibility to remove this option? 
Hope someone can help me. Thanks in advance!

**Comment by dosubot** [comment]
Hey @SaJu84! 👋 I'm here to help you with any bugs, questions, or contributions you have.


I found a similar unsolved discussion and some related issues that might help you:

1. [Feature Request: Disable Export Buttons and Dropdown Options for Users Without Export Permissions](https://github.com/apache/superset/discussions/29079) <sup>[[1]](https://github.com/apache/superset/discussions/29079)</sup>.
2. [Not possible to disable export to json on charts](https://github.com/apache/superset/issues/19535) (closed) <sup>[[2]](https://github.com/apache/superset/issues/19535)</sup>.
3. [Export Dashboard button cannot be hidden](https://github.com/apache/superset/issues/19531) (closed) <sup>[[3]](https://github.com/apache/superset/issues/19531)</sup>.
4. [Disable Export permission from role in list of dashboards](https://github.com/apache/superset/issues/20054) (closed) <sup>[[4]](https://github.com/apache/superset/issues/20054)</sup>.

To disable the JSON download and the copy to clipboard option for a custom role in Superset, you need to ensure that the custom role does not have the necessary permissions to export data. Specifically, the role should not have the `explore_json` permission.

Here is an example of how you can configure the permissions for a custom role in Superset:

1. **Create or Update the Custom Role**: Ensure the custom role does not include the `explore_json` permission.

2. **Assign the Role to Users**: Assign this custom role to the users who should not have access to the JSON download and copy to clipboard options.

Here is a code snippet that shows how to check for the `explore_json` permission in the frontend component:

```tsx
const canExportData = findPermission(
  'explore_json',
  'Superset',
  user?.roles,
);
```

Additionally, the "copy to clipboard" functionality is implemented in the file `superset-frontend/src/utils/copy.ts`. Ensure that your custom role does not include the `can_export_csv` permission to disable these options <sup>[[5]](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/ResultSet/ResultSet.test.tsx)</sup><sup>[[6]](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/ResultSet/index.tsx)</sup><sup>[[7]](https://github.com/apache/superset/blob/master/superset-frontend/src/components/CopyToClipboard/index.tsx)</sup>.

By ensuring that these permissions are not granted to the custom role, you can restrict the JSON download and copy to clipboard options effectively.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by SaJu84** [reply]
Hi @dosu, thanks for the fast reply, but I am still lost.  The role does definetely not have these two permissions (explore_json and can_export_csv), but the export does still work.  Could there be an issue with the superset docker-image we are using (apachesuperset.docker.scarf.sh/apache/superset:4.0.2)?

**Reply by dosubot** [reply]
Yes, there could be an issue with the Superset Docker image you are using (`apachesuperset.docker.scarf.sh/apache/superset:4.0.2`) that allows export to JSON and CSV despite the role not having the `explore_json` and `can_export_csv` permissions.

The code in `superset/views/core.py` shows that the `explore_json` endpoint is decorated with `@permission_name("explore_json")`, which should enforce the `explore_json` permission. Similarly, the code checks for the `can_csv` permission before allowing CSV export:

```python
if (
    response_type == ChartDataResultFormat.CSV
    and not security_manager.can_access("can_csv", "Superset")
):
    return json_error_response(
        _("You don't have the rights to download as csv"),
        status=403,
    )
```

Additionally, the frontend code in `superset-frontend/src/SqlLab/components/ResultSet/index.tsx` also checks for the `can_export_csv` permission before rendering the CSV export button:

```tsx
const canExportData = findPermission(
  'can_export_csv',
  'SQLLab',
  user?.roles,
);

{csv && canExportData && (
  <Button
    buttonSize="small"
    href={getExportCsvUrl(query.id)}
    data-test="export-csv-button"
    onClick={() => logAction(LOG_ACTIONS_SQLLAB_DOWNLOAD_CSV, {})}
  >
    <i className="fa fa-file-text-o" /> {t('Download to CSV')}
  </Button>
)}
```

Furthermore, the integration tests in `tests/integration_tests/security_tests.py` confirm that permissions like `can_csv` and `can_explore_json` are indeed checked and enforced. For example:

```py
self.assertIn(("can_csv", "Superset"), gamma_perm_set)
self.assertIn(("can_explore_json", "Superset"), gamma_perm_set)
```

If these permissions are not being enforced correctly, it could be due to a bug in the specific version of the Docker image you are using <sup>[[1]](https://github.com/apache/superset/blob/master/superset/views/core.py)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/ResultSet/index.tsx)</sup><sup>[[3]](https://github.com/apache/superset/blob/master/tests/integration_tests/security_tests.py)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by SaJu84** [reply]
@dosu can you propose a working docker image with superset v 4.0.2 to me?

**Reply by dosubot** [reply]
Here is a working Docker image configuration for Superset v4.0.2:

```dockerfile
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
FROM python:3.10-slim-bookworm

RUN useradd --user-group --create-home --no-log-init --shell /bin/bash superset

# Configure environment
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN apt-get update -y

# Install dependencies to fix `curl https support error` and `delaying package configuration warning`
RUN apt-get install -y apt-transport-https apt-utils

# Install superset dependencies
# https://superset.apache.org/docs/installation/installing-superset-from-scratch
RUN apt-get install -y build-essential libssl-dev \
    libffi-dev python3-dev libsasl2-dev libldap2-dev libxi-dev chromium

# Install nodejs for custom build
# https://nodejs.org/en/download/package-manager/
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

RUN mkdir -p /home/superset
RUN chown superset /home/superset

WORKDIR /home/superset
ARG VERSION=4.0.2

# Can fetch source from svn or copy tarball from local mounted directory
RUN svn co https://dist.apache.org/repos/dist/dev/superset/$VERSION ./
RUN tar -xvf *.tar.gz
WORKDIR apache-superset-$VERSION

RUN cd superset-frontend \
    && npm ci \
    && npm run build \
    && rm -rf node_modules
WORKDIR /home/superset/apache-superset-$VERSION
RUN pip install --upgrade setuptools pip \
    && pip install -r requirements/base.txt \
    && pip install --no-cache-dir .

RUN flask fab babel-compile --target superset/translations

ENV PATH=/home/superset/superset/bin:$PATH \
    PYTHONPATH=/home/superset/superset/:$PYTHONPATH
COPY from_tarball_entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

Additionally, you can use the following `docker-compose.yml` configuration to set up the necessary services for Superset:

```yml
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# -----------------------------------------------------------------------
# We don't support docker compose for production environments.
# If you choose to use this type of deployment make sure to
# create you own docker environment file (docker/.env) with your own
# unique random secure passwords and SECRET_KEY.
# -----------------------------------------------------------------------
x-superset-image: &superset-image apachesuperset.docker.scarf.sh/apache/superset:${TAG:-latest-dev}
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes:
  &superset-volumes # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - superset_home:/app/superset_home

services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data

  db:
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    image: postgres:15
    container_name: superset_db
    restart: unless-stopped
    volumes:
      - db_home:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  superset:
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 8088:8088
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  superset-init:
    image: *superset-image
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

  superset-worker:
    image: *superset-image
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME",
        ]

  superset-worker-beat:
    image: *superset-image
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file:
      - path: docker/.env # default
        required: true
      - path: docker/.env-local # optional override
        required: false
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
```

This configuration sets up the necessary services (Redis, PostgreSQL, Superset) and ensures that Superset v4.0.2 runs correctly <sup>[[1]](https://github.com/apache/superset/blob/master/RELEASING/Dockerfile.from_svn_tarball)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/docker-compose-image-tag.yml)</sup><sup>[[3]](https://github.com/apache/superset/blob/master/docker/README.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
