### DISCUSSION TITLE
Deploy superset node with replicaCount > 1

### DISCUSSION THREAD

**Discussion by fzhan** [apache/superset#30231] [Q&A / Help]
Hi,

Has anyone experienced with more than one superset node? https://github.com/apache/superset/blob/master/helm/superset/values.yaml#L252

After autoscaling, there seems to be some kind of static generated js not found?

**Comment by dosubot** [comment]
Deploying Superset with multiple replicas requires careful management of static assets and session data to ensure consistency across nodes.

1. **Static Asset Management**:
   - Superset handles static assets by specifying paths to version information and package files, and configuring favicons. You can set a prefix for all static asset paths, which is useful for hosting assets in an external CDN:
     ```python
     STATIC_ASSETS_PREFIX = ""
     ```
   - Static resources are cached with a maximum age of one year:
     ```python
     SEND_FILE_MAX_AGE_DEFAULT = int(timedelta(days=365).total_seconds())
     ```
   - Ensure that static assets are available across all replicas by using a shared storage solution or a CDN <sup>[[1]](https://github.com/apache/superset/blob/master/superset/config.py)</sup>.

2. **Session Management**:
   - Superset uses Redis for session storage, which is configured as a dependency in the Helm chart. This ensures that session data is stored in a centralized, stateful service accessible by all replicas:
     ```yaml
     | https://charts.bitnami.com/bitnami | redis | 17.9.4 |
     ```
   - This setup allows multiple Superset replicas to share session data, ensuring consistency and statefulness across the scaled instances <sup>[[2]](https://github.com/apache/superset/blob/master/helm/superset/README.md)</sup>.

3. **Configuration for Multiple Replicas**:
   - Enable replicas and set the desired number of replicas in the `values.yaml` file:
     ```yaml
     supersetNode:
       replicas:
         enabled: true
         replicaCount: <desired_number_of_replicas>
     ```
   - Adjust resource settings to optimize performance for multiple replicas:
     ```yaml
     resources:
       limits:
         cpu: 500m
         memory: 512Mi
       requests:
         cpu: 250m
         memory: 256Mi
     ```
   - Configure health checks (startup and liveness probes) to ensure the health of the Superset nodes <sup>[[3]](https://github.com/apache/superset/blob/master/helm/superset/values.yaml)</sup>.

By following these practices, you can effectively deploy Superset with multiple replicas and manage static assets and session data across nodes.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
