### DISCUSSION TITLE
How to custom Superset looks and theme

### DISCUSSION THREAD

**Discussion by ptdtan** [apache/superset#30604] [General]
Hi @dosu, I'm new to Superset, how can I custom Superset looks and theme to fit my branding?

**Comment by dosubot** [comment]
Hey @ptdtan! I'm here to help you with Superset customization and any other questions you might have. Let's get started!


To customize the appearance and theme of Superset to fit your branding, you can modify the `defaultTheme` object in the `superset-frontend/packages/superset-ui-core/src/style/index.tsx` file. This object contains properties that define the visual aspects of the application, such as colors and typography.

For example, to change the primary color scheme, update the `primary` color object:

```tsx
const defaultTheme = {
  colors: {
    primary: {
      base: '#20A7C9', // Change this to your brand's primary color
      // other color variations
    },
    // other color objects
  },
  // other properties
};
```

You can also adjust typography settings to match your brand's font styles:

```tsx
typography: {
  families: {
    sansSerif: `'Inter', Helvetica, Arial`, // Change to your brand's font
    // other font settings
  },
  // other typography settings
},
```

Additionally, you can use the `THEME_OVERRIDES` configuration in the `superset/config.py` file to apply custom themes. This allows you to define specific theme properties such as border radius and color schemes:

```py
THEME_OVERRIDES = {
  "borderRadius": 4,
  "colors": {
    "primary": {
      "base": 'red', // Change this to your brand's primary color
    },
    // other color settings
  }
}
```

By modifying these properties, you can align Superset's appearance with your brand's visual identity <sup>[[1]](https://github.com/apache/superset/blob/master/superset-frontend/packages/superset-ui-core/src/style/index.tsx)</sup><sup>[[2]](https://github.com/apache/superset/blob/master/superset/config.py)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by kaimu-kun** [reply]
@dosu Can I also change the font using THEME_OVERRIDES?

**Reply by rohitushur** [reply]
How can i use these in values.yaml file ? I couldnt find kubernetes specific code related to this

**Reply by jarey-ds** [reply]
@rohitushur if using the Helm chart and superset 4.x, you can define the same entries declared above for the THEME_OVERRIDES env variable, in the following values.yaml section:

```yaml
configOverrides:
  themeoverrides: |
    THEME_OVERRIDES = {
      "borderRadius": 4,
      "colors": {
        "primary": {
        "base": 'red',
        },
      }
    }
```
If you're using superset 5.x, you can use the new method, described here: https://superset.apache.org/docs/configuration/theming#1--create-a-theme

example:
```yaml
configOverrides:
  theme: |
    THEME = {
      "token": {
         "colorBgBase": "#faad14"
        }
      }
```
