### DISCUSSION TITLE
Add an image into Superset dashboard

### DISCUSSION THREAD

**Discussion by SumitKShepHertz** [apache/superset#30902] [Ideas]
We are trying to upload an image into our dashboard but for the life of us we are not able to do it. Adding a png image to a dashboard should be easy and straightforward.

**Comment by dosubot** [comment]
Hey @SumitKShepHertz! I'm here to help you out with any bugs, questions, or contributions you have. Let's tackle this image upload together! 👋


You can embed static images in an Apache Superset dashboard using Markdown components. Here's an example of how you can do it with an HTML `<img>` tag within a Markdown component:

```yaml
MARKDOWN--example:
  children: []
  id: MARKDOWN--example
  meta:
    code: <img src="https://your-image-url.com/image.png" alt="Description of image">
    height: 100
    width: 100
  parents:
    - ROOT_ID
    - GRID_ID
    - ROW-example
    - COLUMN-example
  type: MARKDOWN
```

Replace `"https://your-image-url.com/image.png"` with the URL of your image. This method allows you to display static images in your dashboard <sup>[[1]](https://github.com/apache/superset/blob/master/superset/examples/configs/dashboards/Slack_Dashboard.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
