### DISCUSSION TITLE
Error Deploying Superset on Docker: Mounting Path Issue with Nginx Configuration

### DISCUSSION THREAD

**Discussion by adhamenaya** [apache/superset#31354] [Q&A / Help] [answered]
I am trying to deploy superset on docker container, I received this error:

`Started Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/compose/154/docker/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /data/compose/154/docker/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

I using the the same docker-compose.yml comes in git repo, this error is in this part:
```
  nginx:
    image: nginx:latest
    container_name: superset_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
```

**Observed Behavior:**
The deployment fails with the error message above. The issue seems to relate to the nginx.conf file being mounted as a volume.

**What I Checked:**
Confirmed that the file ./docker/nginx/nginx.conf exists in the project directory.
Verified that the path is correct relative to the docker-compose.yml file.
**Question:**
What could be causing this error, and how do I fix it? Is there a mismatch between the expected file type and the host path?

**Environment:**
Docker Version: 2.27
Superset Version: latest version from repo
