### DISCUSSION TITLE
Superset API - Auth Token has a wrong "subject" type

### DISCUSSION THREAD

**Discussion by Mitabula** [apache/superset#31418] [Q&A / Help]
Hello together,

I would like to automate the process of importing Dashboards, but it seems to fail at the first step which is the authentication:
So this is my Ansible playbook so far:

```yaml
- name: Get Token
  uri:
    url: "https://{{ groups['dashboard'][0] }}/api/v1/security/login"
    method: POST
    body_format: json
    body:
      username: "admin"
      password: "admin"
      provider: "db"
    return_content: true
    validate_certs: true
    ca_path: "{{ superset_ssl_cert }}"
  register: __token

- debug:
    msg: "{{ __token.json.access_token }}"

- name: Get CSRF token
  uri:
    headers:
      Authorization: "Bearer {{ __token.json.access_token }}"
    url: "https://{{ groups['dashboard'][0] }}/api/v1/security/csrf_token/"
    method: GET
    return_content: true
    validate_certs: true
    ca_path: "{{ superset_ssl_cert }}"
  register: __csrf_result

- debug:
    msg: "{{ __csrf_result }}"
```

My Access Token seems to look like this:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNzM0MDAyMzI3LCJqdGkiOiIwZDIzMGEyNS1hMjM2LTQzYjItYWI3Yy0wMzViNjM5ZWRkZjEiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE3MzQwMDIzMjcsImNzcmYiOiI4NDFiM2E5My0zYmU2LTQ0NzQtYTIyMS1kN2YxMzEyZmRiZGIiLCJleHAiOjE3MzQwMDMyMjd9.epPSDPtfPZns6xqufeFPrYBiPv8EcopWC70MHz07u0Q
```

Now the Problem which is returned by the "Get CSRF Token" Task:
```
    "json": {
        "msg": "Subject must be a string"
    },
    "msg": "Status code was 422 and not [200]: HTTP Error 422: UNPROCESSABLE ENTITY",
 ```
 
 If i Decode the Token the Payload indeed looks like that "sub" is an integer:
 ```
 {
  "fresh": true,
  "iat": 1734001411,
  "jti": "141b1f8d-6abf-4b1d-9ef7-234ce0314f36",
  "type": "access",
  "sub": 1,
  "nbf": 1734001411,
  "csrf": "d9421511-75f0-4696-bc27-7c96a4b3e7a5",
  "exp": 1734002311
}
```

But the question is: How can i deal with this?
I expected that Superset returns an token i can use again to authenticate other API tasks.

Thanks
