### DISCUSSION TITLE
Values to align center in Big Number chart

### DISCUSSION THREAD

**Discussion by kpreeth** [apache/superset#31455] [Q&A / Help] [answered]
We have a requirement where we need to display the values in center of Big Number chart after adding it in dashboard. Can it be done with CSS?

**Comment by kpreeth** [comment]
@dosu is there any way this can be achieved in css?

**Reply by dosubot** [reply, marked as answer]
Yes, you can center the values in a Big Number chart using CSS. You can achieve this by targeting the specific class or ID of the Big Number chart and applying CSS styles to center the text. Here's a basic example:

```css
.big-number-chart-class {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%; /* Ensure the container takes full height */
    text-align: center;
}
```

Replace `.big-number-chart-class` with the actual class or ID used by the Big Number chart in your application. You may need to inspect the chart element to find the correct selector. Adjust the styles as needed to fit your specific layout requirements.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/296598ff-430d-47e2-ac68-fdd04a183a62?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/296598ff-430d-47e2-ac68-fdd04a183a62?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/296598ff-430d-47e2-ac68-fdd04a183a62?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/296598ff-430d-47e2-ac68-fdd04a183a62?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/296598ff-430d-47e2-ac68-fdd04a183a62?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/296598ff-430d-47e2-ac68-fdd04a183a62?feedback_type=other)</sup>
