### DISCUSSION TITLE
how to run superset with subpath using traefik

### DISCUSSION THREAD

**Discussion by sino1641** [apache/superset#31570] [Q&A / Help] [answered]
Hi Community,
I am new to superset and would like to test it in my k8s cluster but facing trouble on expose it on my domain with subpath.
Searching both issues and discussions, I have already added ENABLE_PROXY_FIX and SUPERSET_WEBSERVER_BASE_URL in config.py but no luck.

Here is my traefik config:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: superset
  namespace: superset
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`my.domain`) && PathPrefix(`/superset`)
      middlewares:
        - name: superset-stripprefix
      services:
        - name: superset2024
          port: 8088
    - kind: Rule
      match: Host(`my.domain`) && PathPrefix(`/static`)
      services:
        - name: superset-2024
          port: 8088
---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: superset-stripprefix
  namespace: superset
spec:
  stripPrefix:
    prefixes:
      - /superset
    forceSlash: false

```

When I visit my.domain/superset, it will redirect to /superset/welcome but it is a 404 page. 
<img width="1074" alt="Snipaste_2024-12-20_01-20-53" src="https://github.com/user-attachments/assets/8bce0bf5-1428-43ab-b4be-410bd1cf0961" />
The picture is from my.domain/static so I also added a middleware to get it shown but obviously it doesn't solve the problem.
Return home is `<a href="/" class="button">Back to home</a>` which also indicates BASE_URL is not set properly.

Do you guys have any idea or if you have tried setting up with traefik as well? Sincerely thanks for any suggestions!
