### DISCUSSION TITLE
fixed

### DISCUSSION THREAD

**Discussion by IlayBor** [apache/superset#31584] [Q&A / Help]

**Comment by dosubot** [comment]
Hey @IlayBor! I'm here to help you with your Superset deployment using the Helm chart. Let's get to the bottom of this together.


I found two similar unsolved discussions that might be relevant to your issue:

1. [Superset redirects to http from https](https://github.com/apache/superset/discussions/18330) <sup>[[1]](https://github.com/apache/superset/discussions/18330)</sup>.
2. [SSL with NLB and ACM on EKS](https://github.com/apache/superset/discussions/19785) <sup>[[2]](https://github.com/apache/superset/discussions/19785)</sup>.

Regarding your configuration, here are a few points to consider:

1. **ENABLE_PROXY_FIX**: This setting should be `True` when Superset is behind a proxy, as it allows the application to correctly interpret the `X-Forwarded` headers. This is crucial for handling HTTPS requests properly <sup>[[3]](https://github.com/apache/superset/blob/master/superset/config.py)</sup>.

2. **PREFERRED_URL_SCHEME**: Ensure that this is set to `https` to indicate that the preferred URL scheme for generating URLs is HTTPS. This helps in maintaining the HTTPS scheme throughout the application <sup>[[3]](https://github.com/apache/superset/blob/master/superset/config.py)</sup>.

3. **SESSION_COOKIE_SECURE**: Setting this to `True` ensures that session cookies are only sent over HTTPS connections, which is important for security when using HTTPS <sup>[[4]](https://github.com/apache/superset/blob/master/docs/docs/security/security.mdx)</sup>.

Make sure that your ALB and ingress are correctly configured to handle HTTPS and that they are forwarding the necessary headers to Superset. Additionally, verify that your Helm chart values are correctly applied and that there are no typos or misconfigurations in your `values.yaml` file.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/61e01aa9-52e8-40a4-8dd8-742e5fd358a9?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/61e01aa9-52e8-40a4-8dd8-742e5fd358a9?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/61e01aa9-52e8-40a4-8dd8-742e5fd358a9?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/61e01aa9-52e8-40a4-8dd8-742e5fd358a9?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/61e01aa9-52e8-40a4-8dd8-742e5fd358a9?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/61e01aa9-52e8-40a4-8dd8-742e5fd358a9?feedback_type=other)</sup>

**Comment by IlayBor** [comment]


**Reply by dosubot** [reply]
A 302 redirect during the login process in Superset can occur due to several reasons, often related to misconfigurations in handling HTTPS or session management. Here are a few things to check:

1. **Session Management**: Ensure that your session management settings are correctly configured. The `SESSION_COOKIE_SECURE` setting should be `True` to ensure cookies are only sent over HTTPS. However, this requires that your entire setup, including the load balancer and ingress, is correctly handling HTTPS <sup>[[1]](https://github.com/apache/superset/blob/master/docs/docs/security/security.mdx)</sup>.

2. **Proxy Headers**: Since you're using an ALB with ingress, make sure that the `X-Forwarded-Proto` header is being set to "https". This is crucial for Superset to understand that the original request was made over HTTPS. You have already set `ENABLE_PROXY_FIX = True`, which is correct for handling these headers <sup>[[2]](https://github.com/apache/superset/blob/master/docs/docs/configuration/configuring-superset.mdx)</sup>.

3. **PREFERRED_URL_SCHEME**: This should be set to `https` to ensure that all generated URLs use the HTTPS scheme, which you've already configured <sup>[[2]](https://github.com/apache/superset/blob/master/docs/docs/configuration/configuring-superset.mdx)</sup>.

4. **Ingress and ALB Configuration**: Double-check your ingress and ALB settings to ensure they are correctly configured to handle HTTPS and forward the necessary headers to Superset.

If these configurations are correct and the issue persists, it might be helpful to look into the specific logs and configurations of your ingress and ALB to ensure they are not causing the redirect loop.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/24634753-7661-4431-a658-c26d3ef20523?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/24634753-7661-4431-a658-c26d3ef20523?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/24634753-7661-4431-a658-c26d3ef20523?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/24634753-7661-4431-a658-c26d3ef20523?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/24634753-7661-4431-a658-c26d3ef20523?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/24634753-7661-4431-a658-c26d3ef20523?feedback_type=other)</sup>

**Comment by IlayBor** [comment]
I added more info on the problem
any help would be extremely appreciated

**Reply by surajsoliish** [reply]
i resolved this with classic loadbalancer instead of ALB and it works like charm

**Reply by IlayBor** [reply]
can you elaborate? or give an example of the yaml?
what do I need to change (I guess in the annotations)

**Reply by surajsoliish** [reply]
Add Helm Repositories:
```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update
```
Install NGINX Ingress Controller:
`helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
`
Install Cert-Manager:
`kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml`


Create a ClusterIssuer for Let's Encrypt: Create a file cluster-issuer.yaml with the following content:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
```

update your superset helm values.yaml file with the following configuration:
```
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  tls:
    - hosts:
        - example.com
      secretName: superset-tls
  hosts:
    - example.com
  path: /
  pathType: Prefix
```
