### DISCUSSION TITLE
Ingress hostname should be templated

### DISCUSSION THREAD

**Discussion by LucasRakotomalala** [apache/superset#31736] [Ideas]
Hello,
I have a use case in which I want to deploy in different Kubernetes namespaces multiple Superset instance.
But since ingress hostname is not templated, the ingress hostname cannot depend on the release name and the release namespace.

## Reproduction Steps

1. Among other configurations, put the following:

```yaml
# values.yaml
ingress:
  enabled: true
  pathType: Prefix
  hosts:
    - superset.test.svc.cluster.local
 ```

2. Deploy Superset on at least 2 different namespaces (e.g. `default` and `test`), using the same `values.yaml`
3. See that the installation on the second namespace fails with this error:
```txt
Error: INSTALLATION FAILED: 1 error occurred:
        * admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "superset.test.svc.cluster.local" and path "/" is already defined in ingress default
```

## Ideas

In my opinion, the hosts should be templated, to be able to put the following in `values.yaml`:
```yaml
ingress:
  hosts:
    - superset.{{ .Release.Namespace }}.svc.cluster.local
 ```

Also, in Bitnami Charts, it is currently supported.

### Files impacted

Only one file should be impacted by having such a feature:

- [ingress.yaml#L54](https://github.com/apache/superset/blob/master/helm/superset/templates/ingress.yaml#L54)

Also, the default way to add host to the ingress will still work.
