### DISCUSSION TITLE
How to enable SSO login using microsoft azure,  having xml file of metadata, deploying using Helmchart

### DISCUSSION THREAD

**Discussion by devyash786** [apache/superset#32787] [Q&A / Help]
How to enable SSO login using microsoft azure,  having xml file of metadata, deploying using Helmchart

**Comment by dosubot** [comment]
I found a similar unsolved discussion regarding SAML Integration in Apache Superset, which might be relevant to your query. You can check it out [here](https://github.com/apache/superset/discussions/32786) <sup>[[1]](https://github.com/apache/superset/discussions/32786)</sup>.

For enabling SSO with Microsoft Azure in Apache Superset, you can follow these steps:

1. **Install the AuthLib package**: This is necessary for handling OAuth authentication.

2. **Configure OAuth settings**: Update your Superset configuration file with the necessary OAuth settings. Here's an example configuration:

   ```python
   from flask_appbuilder.security.manager import AUTH_OAUTH

   AUTH_TYPE = AUTH_OAUTH
   AUTH_USER_REGISTRATION = True
   AUTH_USER_REGISTRATION_ROLE = 'Public'

   OAUTH_PROVIDERS = [{
       'name': 'azure',
       'token_key': 'access_token',
       'icon': 'fa-windows',
       'remote_app': {
           'client_id': 'your_client_id',
           'client_secret': 'your_client_secret',
           'api_base_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2',
           'access_token_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/token',
           'authorize_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/authorize',
           'client_kwargs': {
               'scope': 'openid email name profile User.Read GroupMember.Read.All upn'
           }
       }
   }]

   AUTH_ROLES_MAPPING = {
       'Gamma': ['Gamma'],
       'Admin': ['Admin']
   }
   ```

3. **Custom Security Manager**: Implement a custom security manager to handle user information retrieval. Create a file named `custom_sso_security_manager.py`:

   ```python
   def oauth_user_info(self, provider, response=None):
       logging.debug("Oauth2 provider: {0}.".format(provider))
       if provider == 'azure':
           me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
           logging.debug("user_data: {0}".format(me))
           return {
               'name': me['name'],
               'email': me['email'],
               'id': me['user_name'],
               'username': me['user_name'],
               'first_name': '',
               'last_name': ''
           }
   ```

4. **Update `superset_config.py`**: Use the custom security manager:

   ```python
   from custom_sso_security_manager import CustomSsoSecurityManager
   CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
   ```

Regarding the deployment using Helm charts and handling SAML metadata XML files, I couldn't find specific instructions in the repository. You might need to adapt the Helm chart values to include these configurations, but the exact steps are not documented in the available sources.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/5c8efbef-e518-4320-b1be-7d9b11bc90d6?feedback_type=other)</sup>

**Reply by devyash786** [reply]
@dosu
Please give the file structure and whole code for yaml and py files

**Reply by dosubot** [reply]
I couldn't find specific instructions for the file structure and complete code for YAML and Python files related to enabling SSO with Microsoft Azure using Helm charts in the Apache Superset repository. However, I can provide a general guideline on how you might structure your files and configurations:

### File Structure

Here's a suggested file structure for deploying Apache Superset with SSO using Helm charts:

```
superset-helm/
│
├── charts/
│   └── superset/
│       ├── templates/
│       │   ├── deployment.yaml
│       │   ├── service.yaml
│       │   └── configmap.yaml
│       ├── values.yaml
│       └── Chart.yaml
│
└── config/
    ├── superset_config.py
    └── custom_sso_security_manager.py
```

### YAML Configuration

**`values.yaml`**

This file contains the configuration values for your Helm chart. You can include environment variables and other settings here:

```yaml
configOverrides:
  SUPERSET_CONFIG_PATH: /app/superset_config.py

extraEnv:
  - name: SUPERSET_CONFIG_PATH
    value: /app/superset_config.py

extraSecretEnv:
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-sso-secret
        key: client_id
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: azure-sso-secret
        key: client_secret
```

**`configmap.yaml`**

This file can be used to create a ConfigMap for your `superset_config.py`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: superset-config
data:
  superset_config.py: |
    from custom_sso_security_manager import CustomSsoSecurityManager
    CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
```

### Python Configuration

**`superset_config.py`**

This file contains your Superset configuration, including the custom security manager:

```python
from custom_sso_security_manager import CustomSsoSecurityManager

AUTH_TYPE = AUTH_OAUTH
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Public'

OAUTH_PROVIDERS = [{
    'name': 'azure',
    'token_key': 'access_token',
    'icon': 'fa-windows',
    'remote_app': {
        'client_id': os.environ.get('CLIENT_ID'),
        'client_secret': os.environ.get('CLIENT_SECRET'),
        'api_base_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2',
        'access_token_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/token',
        'authorize_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/authorize',
        'client_kwargs': {
            'scope': 'openid email name profile User.Read GroupMember.Read.All upn'
        }
    }
}]

CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
```

**`custom_sso_security_manager.py`**

This file implements the custom security manager:

```python
from flask_appbuilder.security.manager import AUTH_OAUTH
import logging

class CustomSsoSecurityManager:
    def oauth_user_info(self, provider, response=None):
        logging.debug("Oauth2 provider: {0}.".format(provider))
        if provider == 'azure':
            me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
            logging.debug("user_data: {0}".format(me))
            return {
                'name': me['name'],
                'email': me['email'],
                'id': me['user_name'],
                'username': me['user_name'],
                'first_name': '',
                'last_name': ''
            }
```

This is a general guideline and may need to be adjusted based on your specific requirements and environment.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/2ca48da2-8e20-4364-9175-5bee4aaa9c26?feedback_type=other)</sup>

**Comment by devyash786** [comment]
@Dosu
I want to implement using single file

**Reply by dosubot** [reply]
To implement SSO with Microsoft Azure using a single configuration file in Apache Superset, you can consolidate your settings into the `superset_config.py` file. Here's how you can structure it:

### `superset_config.py`

This file will contain all necessary configurations, including OAuth settings and the custom security manager:

```python
import os
from flask_appbuilder.security.manager import AUTH_OAUTH
import logging

# Set the authentication type to OAuth
AUTH_TYPE = AUTH_OAUTH
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = 'Public'

# Define the OAuth provider configuration
OAUTH_PROVIDERS = [{
    'name': 'azure',
    'token_key': 'access_token',
    'icon': 'fa-windows',
    'remote_app': {
        'client_id': os.environ.get('CLIENT_ID'),  # Use environment variable for client ID
        'client_secret': os.environ.get('CLIENT_SECRET'),  # Use environment variable for client secret
        'api_base_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2',
        'access_token_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/token',
        'authorize_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/authorize',
        'client_kwargs': {
            'scope': 'openid email name profile User.Read GroupMember.Read.All upn'
        }
    }
}]

# Custom security manager class
class CustomSsoSecurityManager:
    def oauth_user_info(self, provider, response=None):
        logging.debug("Oauth2 provider: {0}.".format(provider))
        if provider == 'azure':
            me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
            logging.debug("user_data: {0}".format(me))
            return {
                'name': me['name'],
                'email': me['email'],
                'id': me['user_name'],
                'username': me['user_name'],
                'first_name': '',
                'last_name': ''
            }

# Assign the custom security manager
CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
```

### Deployment with Helm

In your Helm chart, ensure that the `superset_config.py` is included as part of your deployment. You can use a ConfigMap or a Secret to manage this file, depending on your security requirements. Set the `SUPERSET_CONFIG_PATH` environment variable to point to this file.

### Environment Variables

Ensure that the environment variables `CLIENT_ID` and `CLIENT_SECRET` are set in your deployment configuration, either through Kubernetes Secrets or directly in your Helm chart's `values.yaml` file.

This approach allows you to manage all configurations within a single file, simplifying deployment and maintenance.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/56e6a3fa-b279-4295-ac25-b0a6c27e9789?feedback_type=other)</sup>

**Reply by devyash786** [reply]
@dosu
I am only using a fileName.yaml file, suggest changes in that

**Reply by dosubot** [reply]
To configure SSO with Microsoft Azure using a single `fileName.yaml` for your Helm deployment, you can include all necessary configurations directly in this YAML file. Here's an example of how you might structure it:

```yaml
# fileName.yaml

# Configuration for Superset
configOverrides:
  SUPERSET_CONFIG_PATH: /app/superset_config.py

# Environment variables for OAuth
extraEnv:
  - name: SUPERSET_CONFIG_PATH
    value: /app/superset_config.py

# Use Kubernetes Secrets for sensitive information
extraSecretEnv:
  - name: CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: azure-sso-secret
        key: client_id
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: azure-sso-secret
        key: client_secret

# Custom configuration for OAuth with Microsoft Azure
configOverrides:
  enable_oauth: |
    from flask_appbuilder.security.manager import AUTH_OAUTH
    import logging

    AUTH_TYPE = AUTH_OAUTH
    AUTH_USER_REGISTRATION = True
    AUTH_USER_REGISTRATION_ROLE = 'Public'

    OAUTH_PROVIDERS = [{
        'name': 'azure',
        'token_key': 'access_token',
        'icon': 'fa-windows',
        'remote_app': {
            'client_id': os.environ.get('CLIENT_ID'),
            'client_secret': os.environ.get('CLIENT_SECRET'),
            'api_base_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2',
            'access_token_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/token',
            'authorize_url': 'https://login.microsoftonline.com/your_tenant_id/oauth2/authorize',
            'client_kwargs': {
                'scope': 'openid email name profile User.Read GroupMember.Read.All upn'
            }
        }
    }]

    class CustomSsoSecurityManager:
        def oauth_user_info(self, provider, response=None):
            logging.debug("Oauth2 provider: {0}.".format(provider))
            if provider == 'azure':
                me = self.appbuilder.sm.oauth_remotes[provider].get('userDetails').data
                logging.debug("user_data: {0}".format(me))
                return {
                    'name': me['name'],
                    'email': me['email'],
                    'id': me['user_name'],
                    'username': me['user_name'],
                    'first_name': '',
                    'last_name': ''
                }

    CUSTOM_SECURITY_MANAGER = CustomSsoSecurityManager
```

### Key Points:
- **Environment Variables**: Use `extraEnv` and `extraSecretEnv` to manage environment variables, especially for sensitive data like `CLIENT_ID` and `CLIENT_SECRET`.
- **OAuth Configuration**: The `configOverrides` section includes the necessary Python code to configure OAuth with Microsoft Azure.
- **Security Manager**: The custom security manager is defined within the `configOverrides` to handle user information retrieval.

Ensure that your Kubernetes cluster has the necessary secrets (`azure-sso-secret`) set up to provide the `client_id` and `client_secret`. Adjust the paths and values according to your specific deployment setup.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/b05aea44-46eb-48de-9b29-9468a2c5569c?feedback_type=other)</sup>
