### ISSUE TITLE
Can I run a app within the superset docker-compose.yml with a specific db,user and password? 

### ISSUE THREAD

**Issue by 00KL** [apache/superset#12670]
I tryed edit the docker-compose file with this code:
I change the original "db" service to:
```
db:
              env_file: docker/.env
              image: postgres:10
              container_name: superset_db
              restart: unless-stopped
              environment:
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=1234
                - POSTGRES_DB=sro_ontology
              ports:
                - "127.0.0.1:5432:5432"
              volumes:
                - db_home:/var/lib/postgresql/data
```

And tryed to run the app service by adding:
```
app:
    build: ./python_tuto
    environment:
      - USERDB=postgres
      - PASSWORDDB=1234
      - DBNAME=sro_ontology
      - HOST=db
    depends_on:
      - db
```
The python_tuto folder was added on the superset folder.
