### ISSUE TITLE
Can't open Settings -> List Users when using OAuth with Google for an Admin user

### ISSUE THREAD

**Issue by pingusix** [apache/superset#13243]
### Expected results

User list displays and users can be edited When settings -> List Users is selected

### Actual results

Get an access denied popup and return to dashboard

#### How to reproduce the bug

Enable AUTH_TYPE=AUTH_OAUTH in config.py

Snippet of config.py: 
 
AUTH_TYPE = AUTH_OAUTH
AUTH_USER_REGISTRATION = True
AUTH_USER_REGISTRATION_ROLE = "Admin"
PUBLIC_ROLE_LIKE_GAMMA = True
OAUTH_PROVIDERS = [
    {
        "name": "google",
        "icon": "fa-google",
        "token_key": "access_token",
        "remote_app": {
            "client_id": "xxx",
            "client_secret": "xxx",
            "api_base_url": "https://www.googleapis.com/oauth2/v2/",
            "client_kwargs": {"scope": "email profile"},
            "request_token_url": None,
            "access_token_url": "https://accounts.google.com/o/oauth2/token",
            "authorize_url": "https://accounts.google.com/o/oauth2/auth",
        }
    }
]

Register a new user using Google as a provider. 
Go to settings-> List Users

Also changed auth type back to AUTH_DB and logged in as admin. I then deleted permissions for new google-based admin user and added them back in so they matched the currently authorised admin. Logged out, changed config.py back to use oauth and logged in as google-based admin user. Problem remains (also created  a new auth_db based user with same permissions and worked correctly)

### Environment

(please complete the following information):

Ubuntu 18.04.3
Superset 1.0.1
Python 3.7.5
Node 8.10.0

**Comment by rrittsteiger** [comment]
We are also struggling with this problem.

**Comment by danielewood** [comment]
I'm not having this problem with Superset 1.1.0 running on Kubernetes, here is my google auth config for you to compare:

```yaml
extraEnv:
  OAUTH_HOME_DOMAIN: 'mydomain.com'
  OAUTH_WHITELIST_REGEX: '@mydomain.com$'
extraSecretEnv:
  # GCP API Keys: https://console.cloud.google.com/apis/credentials
  # GCP ClientID: superset-oauth2
  GOOGLE_KEY: xxxxxxx.apps.googleusercontent.com
  GOOGLE_SECRET: xxxxxxxxxx
  
configOverrides:
  enable_proxy_fix: |
    # This will make sure the redirect_uri is properly computed, even with SSL offloading
    ENABLE_PROXY_FIX = True
  enable_debug: |
    LOG_LEVEL = 'DEBUG'
  enable_oauth: |
    from flask_appbuilder.security.manager import (AUTH_DB, AUTH_OAUTH)
    AUTH_TYPE = AUTH_OAUTH
    OAUTH_PROVIDERS = [
        {
            "name": "google",
            "whitelist": [ os.getenv("OAUTH_WHITELIST_REGEX", "") ],
            "icon": "fa-google",
            "token_key": "access_token",
            "remote_app": {
                "client_id": os.getenv("GOOGLE_KEY"),
                "client_secret": os.getenv("GOOGLE_SECRET"),
                "api_base_url": "https://www.googleapis.com/oauth2/v2/",
                "client_kwargs": {"scope": "email profile"},
                "request_token_url": None,
                "access_token_url": "https://accounts.google.com/o/oauth2/token",
                "authorize_url": "https://accounts.google.com/o/oauth2/auth",
                "authorize_params": {"hd": os.getenv("OAUTH_HOME_DOMAIN", "")}
            }
        }
    ]
    
    # Map Authlib roles to superset roles
    AUTH_ROLE_ADMIN = 'Admin'
    AUTH_ROLE_PUBLIC = 'Public'

    # Will allow user self registration, allowing to create Flask users from Authorized User
    AUTH_USER_REGISTRATION = True

    # The default user self registration role
    AUTH_USER_REGISTRATION_ROLE = "Admin"
```
