### ISSUE TITLE
Helm ExtraConfigs are not loaded

### ISSUE THREAD

**Issue by samudurand** [apache/superset#14520]
The documentation mentions that extra configs can be added via Helm, especially to add data sources on startup. 
```
extraConfigs:
  datasources-init.yaml: |
    databases:
    - allow_csv_upload: true
      allow_ctas: true
      allow_cvas: true
      database_name: example-db
      extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
        metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_csv_upload\": []\r\n\
        }"
      sqlalchemy_uri: example://example-db.local
      tables: []
```
But the config loaded in the container are not loaded by Superset.
To make sure of it , I put a badly formatted yaml in the file, but it didn't trigger any error in Superset startup.

### Expected results

Superset starts with pre-configured datasources/databases.

### Actual results

Nothing

#### How to reproduce the bug

Follow the docs and add an extra config file, with datasources, or even with just bad yaml. Nothing will happen when deploying to kubernetes.

### Environment

Kubernetes

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by amal-v** [comment]
I am also facing the same issue. Trying to findout whether we need to mention this file in any other configuration.

**Comment by stefano-cherchi** [comment]
I've also been struggling with the same issue for two days now. 

Some custom configurations provided through `--values <filename>` are applied, some others are completely ignored. E.g: 

```yaml
postgresql:
  enabled: true/false
```

or 

```yaml
service:
  type: LoadBalancer/ClusterIP
  port: 8088
  annotations: {
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  }
  loadBalancerIP: null
```

are applied, while `postgresHost:`, `extraEnv:`, `extraSecretEnv:`, and others never make it to the env variables passed to the pods ( `$DB_HOST`, `$DB_USER`, `$REDIS_HOST`, etc).

**Comment by PeterHenell** [comment]
The sample values.yaml file is using the wrong filename in extraConfigs.

Changing datasources-init.yaml to import_datasources.yaml solves the issue.

```
extraConfigs:
  import_datasources.yaml: |
    databases:
    - allow_csv_upload: true
      allow_ctas: true
      allow_cvas: true
      database_name: example-db
      extra: "{\r\n    \"metadata_params\": {},\r\n    \"engine_params\": {},\r\n    \"\
        metadata_cache_timeout\": {},\r\n    \"schemas_allowed_for_csv_upload\": []\r\n\
        }"
      sqlalchemy_uri: example://example-db.local
      tables: []
```
