### ISSUE TITLE
[Helm Chart] load DB password from third-party secret

### ISSUE THREAD

**Issue by elyzov** [apache/superset#16245]
**Is your feature request related to a problem? Please describe.**
I use zalando operator to deploy postgresql DB nearby. Zalando operator puts postgresql password to separate secret.
But at the moment, there is no ability to load environment variables from third-party secrets using **valueFrom** syntax.

**Describe the solution you'd like**
I want to introduce one more **extraEnvRaw** variable, which will be injected into the **env** section of container as is:
```
extraEnvRaw:
  - name: DB_PASS
    valueFrom:
      secretKeyRef:
        name: superset.superset-postgres.credentials.postgresql.acid.zalan.do
        key: password
```

**Describe alternatives you've considered**
We can consider one more abstraction over **valueFrom** syntax. But I prefer to implement more general and flexible solution.

**Additional context**
I saw such approach has been used in other charts, like [fluentd chart](https://github.com/fluent/helm-charts/blob/main/charts/fluentd/templates/_pod.tpl#L31).
