### ISSUE TITLE
Running "docker-compose up" fails to compile successfully (Error on importing STR_NA_VALUES from pandas)

### ISSUE THREAD

**Issue by Alvie** [apache/superset#17949]
Running `docker-compose up` on version 1.3.2 (and 1.4.0rc3) fails to compile.

I understand that we are meant to use the non-dev build (i.e. `docker-compose -f docker-compose-non-dev.yml up`) in order to use the superset app when running via docker, but there are also times where we may want to make modifications which would require the `docker-compose up` command to be run?

#### How to reproduce the bug

1. Go to release on the github, download the 1.3.2 zip (https://github.com/apache/superset/archive/refs/tags/1.3.2.zip) (edit: also happens on 1.4.0rc3, you can try it with that too)
2. Extract the folder
3. Enter the superset-1.3.2 folder in a terminal
4. Run `docker-compose up`

### Expected results

I would expect to be presented with the Superset login screen / welcome page when viewing on browser.
![image](https://user-images.githubusercontent.com/8447791/148413182-3deabcab-05ee-4eb4-81e3-72156405c3dc.png)

I would expect it to compile successfully without error.

### Actual results
Presented with stack trace of error when viewing in browser.
![image](https://user-images.githubusercontent.com/8447791/148417674-3d3f21f1-85e1-4974-86ad-85fb81a680eb.png)

The docker logs say this, or similar in most of the containers (app, worker, worker-beat):  
`ImportError: cannot import name 'STR_NA_VALUES' from 'pandas.io.parsers' (/usr/local/lib/python3.8/site-packages/pandas/io/parsers/__init__.py`) in most containers.

More full logs here:
https://0bin.net/paste/QaIy4jLo#n1g3eqjy3UCcxVj6OZ2VLYge32s-nN2aWqLNy7XCTNE

### Environment

(please complete the following information):
- docker: `Docker version 20.10.12, build e91ed57`
- browser type and version: N/A (any / all), tested on ChromeVersion 97.0.4692.71 (Official Build) (64-bit)
- superset version: 1.3.2 / `Superset 0.0.0dev` (according to running command in docker container)
- python version: `Python 3.8.12` (according to running command in docker container)
- node.js version: `OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "node": executable file not found in $PATH: unknown` (according to running command in docker container)
- any feature flags active: Unsure / Only default

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Here is the `pip freeze` on the superset app docker container:
https://0bin.net/paste/aKKgpHJ3#uAUB7QBQyt7wpPXn6d3CPtjoFsnMZI0+oF7VymnAwbO

I see that pandas is on 1.3.4 but in the requirements base.txt it is 1.2.2, so I am not sure how it upgraded itself ( I haven't checked if other packages are correct or not)

Might be related to this? https://github.com/apache/superset/pull/16400

Other user had an error here similar: https://github.com/apache/superset/issues/17333 but I didn't understand how they fixed it.

**Comment by Alvie** [comment]
The pull request from @ravimakhija https://github.com/apache/superset/pull/16400 does seem to fix it, if I set it to use pandas._libs.parsers instead of pandas.io.parsers in the superset/config.py

**Comment by jenseng** [comment]
Just ran into this trying to develop against 1.3, but I was able to resolve it by running `docker build -t apache/superset:latest-dev .`, which made sure I had the right versions of things in the docker image. An alternative workaround might be to find a suitable version [here](https://hub.docker.com/r/apache/superset/tags) and pull it.

docker-compose.yml is configured to use `apache/superset:latest-dev`, which presumably is built from the master branch. So by building locally you can ensure you have the right versions of things for your branch.

**Comment by pdakkata-quot** [comment]
@jenseng thanks man! It helps.

**Comment by pdakkata-quot** [comment]
Cause: Git clone from any branch other than master, doesn’t build & get all the required files/folders for docker to run in development mode.

Solution: The below command should be ran first to get all the required files/folders for docker.
`docker build -t apache/superset:latest-dev . `

Order of execution:
1. Remove all the node modules in superset-frontend folder.
2. delete all volumes in docker related to the existing container. ( `docker-compose down -v` )
3. `docker build -t apache/superset:latest-dev .`
4. `docker-compose up` 
5. Wait until superset-init & superset-node complete.

**Comment by pdakkata-quot** [comment]
> The pull request from @ravimakhija #16400 does seem to fix it, if I set it to use pandas._libs.parsers instead of pandas.io.parsers in the superset/config.py

No need of this, **docker build -t apache/superset:latest-dev .** takes care of it too.

**Comment by Alvie** [comment]
> > The pull request from @ravimakhija #16400 does seem to fix it, if I set it to use pandas._libs.parsers instead of pandas.io.parsers in the superset/config.py
> 
> No need of this, **docker build -t apache/superset:latest-dev .** takes care of it too.

Oh wow that seems like a better option, thank you :)

**Comment by denbon05** [comment]
> **Cause**: Git clone from any branch other than master, doesn’t build & get all the required files/folders for docker to run in development mode.
> 
> **Solution**: The below command should be ran first to get all the required files/folders for docker. `docker build -t apache/superset:latest-dev . `
> 
> **Order of execution**:
> 
> 1. Remove all the node modules in superset-frontend folder.
> 2. delete all volumes in docker related to the existing container. ( `docker-compose down -v` )
> 3. `docker build -t apache/superset:latest-dev .`
> 4. `docker-compose up`
> 5. Wait until superset-init & superset-node complete.

![image](https://user-images.githubusercontent.com/58662935/161535478-75361083-365e-40fe-af8a-13d66d66a8f2.png)
I did the same as you and tried other attempts and didn't get any error (in logs) but the page is not showing

**Comment by pdakkata-quot** [comment]
> > **Cause**: Git clone from any branch other than master, doesn’t build & get all the required files/folders for docker to run in development mode.
> > **Solution**: The below command should be ran first to get all the required files/folders for docker. `docker build -t apache/superset:latest-dev . `
> > **Order of execution**:
> > 
> > 1. Remove all the node modules in superset-frontend folder.
> > 2. delete all volumes in docker related to the existing container. ( `docker-compose down -v` )
> > 3. `docker build -t apache/superset:latest-dev .`
> > 4. `docker-compose up`
> > 5. Wait until superset-init & superset-node complete.
> 
> ![image](https://user-images.githubusercontent.com/58662935/161535478-75361083-365e-40fe-af8a-13d66d66a8f2.png) I did the same as you and tried other attempts and didn't get any error (in logs) but the page is not showing

You need to wait for more than 30 mins to let all the examples & modules load. It'll work.

**Comment by denbon05** [comment]
> > > **Cause**: Git clone from any branch other than master, doesn’t build & get all the required files/folders for docker to run in development mode.
> > > **Solution**: The below command should be ran first to get all the required files/folders for docker. `docker build -t apache/superset:latest-dev . `
> > > **Order of execution**:
> > > 
> > > 1. Remove all the node modules in superset-frontend folder.
> > > 2. delete all volumes in docker related to the existing container. ( `docker-compose down -v` )
> > > 3. `docker build -t apache/superset:latest-dev .`
> > > 4. `docker-compose up`
> > > 5. Wait until superset-init & superset-node complete.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/58662935/161535478-75361083-365e-40fe-af8a-13d66d66a8f2.png) I did the same as you and tried other attempts and didn't get any error (in logs) but the page is not showing
> 
> You need to wait for more than 30 mins to let all the examples & modules load. It'll work. (Since it is the first time, it takes time to load all the examples, tables, modules etc..)

hmm, I've been waiting near by 2 hours and without changes :/

**Comment by pdakkata-quot** [comment]
> > > > **Cause**: Git clone from any branch other than master, doesn’t build & get all the required files/folders for docker to run in development mode.
> > > > **Solution**: The below command should be ran first to get all the required files/folders for docker. `docker build -t apache/superset:latest-dev . `
> > > > **Order of execution**:
> > > > 
> > > > 1. Remove all the node modules in superset-frontend folder.
> > > > 2. delete all volumes in docker related to the existing container. ( `docker-compose down -v` )
> > > > 3. `docker build -t apache/superset:latest-dev .`
> > > > 4. `docker-compose up`
> > > > 5. Wait until superset-init & superset-node complete.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/58662935/161535478-75361083-365e-40fe-af8a-13d66d66a8f2.png) I did the same as you and tried other attempts and didn't get any error (in logs) but the page is not showing
> > 
> > 
> > You need to wait for more than 30 mins to let all the examples & modules load. It'll work. (Since it is the first time, it takes time to load all the examples, tables, modules etc..)
> 
> hmm, I've been waiting near by 2 hours and without changes :/ any errors, any visible results on the page

It should work. Is the image got sucessfully build? can you share screenshots for more understanding?

**Comment by denbon05** [comment]
> > > > > **Cause**: Git clone from any branch other than master, doesn’t build & get all the required files/folders for docker to run in development mode.
> > > > > **Solution**: The below command should be ran first to get all the required files/folders for docker. `docker build -t apache/superset:latest-dev . `
> > > > > **Order of execution**:
> > > > > 
> > > > > 1. Remove all the node modules in superset-frontend folder.
> > > > > 2. delete all volumes in docker related to the existing container. ( `docker-compose down -v` )
> > > > > 3. `docker build -t apache/superset:latest-dev .`
> > > > > 4. `docker-compose up`
> > > > > 5. Wait until superset-init & superset-node complete.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/58662935/161535478-75361083-365e-40fe-af8a-13d66d66a8f2.png) I did the same as you and tried other attempts and didn't get any error (in logs) but the page is not showing
> > > 
> > > 
> > > You need to wait for more than 30 mins to let all the examples & modules load. It'll work. (Since it is the first time, it takes time to load all the examples, tables, modules etc..)
> > 
> > 
> > hmm, I've been waiting near by 2 hours and without changes :/ any errors, any visible results on the page
> 
> It should work. Is the image got sucessfully build? can you share screenshots for more understanding?

Yes, image builded successfuly  (Successfully tagged apache/superset:latest-dev), everything is the same as in apache/superset repo on branch 1.4.1cr1 except docker-compose.yml, because I need to have prodaction version of database seted locally (in docker-compose-non-dev.yml) and dev db in docker container for my experements, I already had this configuration on superset version 1.3.2
```yml
x-superset-image: &superset-image apache/superset:latest-dev
x-superset-user: &superset-user root
x-superset-depends-on: &superset-depends-on
  - db
  - redis
x-superset-volumes: &superset-volumes
  # /app/pythonpath_docker will be appended to the PYTHONPATH in the final container
  - ./docker:/app/docker
  - ./superset:/app/superset
  - ./superset-frontend:/app/superset-frontend
  - superset_home:/app/superset_home
  - ./tests:/app/tests

version: "3.7"
services:
  redis:
    image: redis:latest
    container_name: d_superset_cache
    restart: unless-stopped
    # ports:
    #   - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data

  db:
    env_file: docker/.env
    image: postgres:10
    container_name: d_superset_db
    restart: unless-stopped
    # ports:
    #   - "127.0.0.1:5432:5432"
    volumes:
      - db_home:/var/lib/postgresql/data
      - /home/dbondarenko/Dev/superset/extensions:/dev/db_extensions

  d_superset:
    env_file: docker/.env
    image: *superset-image
    container_name: d_superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app"]
    restart: unless-stopped
    ports:
      - 8099:8088
    user: *superset-user
    depends_on: *superset-depends-on
    volumes: *superset-volumes
    environment:
      CYPRESS_CONFIG: "${CYPRESS_CONFIG}"

  d_superset-websocket:
    container_name: d_superset_websocket
    build: ./superset-websocket
    image: superset-websocket
    ports:
      - 8080:8080
    depends_on:
      - redis
    # Mount everything in superset-websocket into container and
    # then exclude node_modules and dist with bogus volume mount.
    # This is necessary because host and container need to have
    # their own, separate versions of these files. .dockerignore
    # does not seem to work when starting the service through
    # docker-compose.
    #
    # For example, node_modules may contain libs with native bindings.
    # Those bindings need to be compiled for each OS and the container
    # OS is not necessarily the same as host OS.
    volumes:
      - ./superset-websocket:/home/superset-websocket
      - /home/superset-websocket/node_modules
      - /home/superset-websocket/dist
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_SSL=false

  d_superset-init:
    image: *superset-image
    container_name: d_superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: docker/.env
    depends_on: *superset-depends-on
    user: *superset-user
    volumes: *superset-volumes
    environment:
      CYPRESS_CONFIG: "${CYPRESS_CONFIG}"

  d_superset-node:
    image: node:16
    container_name: d_superset_node
    command: ["/app/docker/docker-frontend.sh"]
    env_file: docker/.env
    depends_on: *superset-depends-on
    volumes: *superset-volumes

  d_superset-worker:
    image: *superset-image
    container_name: d_superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: *superset-user
    volumes: *superset-volumes
    # Bump memory limit if processing selenium / thumbails on superset-worker
    # mem_limit: 2038m
    # mem_reservation: 128M

  d_superset-worker-beat:
    image: *superset-image
    container_name: d_superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: docker/.env
    restart: unless-stopped
    depends_on: *superset-depends-on
    user: *superset-user
    volumes: *superset-volumes

  d_superset-tests-worker:
    image: *superset-image
    container_name: d_superset_tests_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env
    environment:
      DATABASE_HOST: localhost
      DATABASE_DB: test
      REDIS_CELERY_DB: 2
      REDIS_RESULTS_DB: 3
      REDIS_HOST: localhost
    network_mode: host
    depends_on: *superset-depends-on
    user: *superset-user
    volumes: *superset-volumes

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  db_extensions:
    external: false
  redis:
    external: false
```

 and few added variables in superset_config.py:
 ```py
SQLLAB_CTAS_NO_LIMIT = True
SUPERSET_WEBSERVER_TIMEOUT = 60 * 30
```
