### ISSUE TITLE
Documentation on how to properly deploy Superset for production environment

### ISSUE THREAD

**Issue by 1c7** [apache/superset#18616]
### Motivation
I am having difficult time figure out how to properly deploy Superset to a production enviroment.   
I am planning to use AWS ECS.   

### Proposed Change
1. I am gonna figure out how to deploy Superset onto the Cloud like AWS in next couple days (by reading https://superset.apache.org/docs/intro and the source code)
2. I am gonna send a Pull Request with a new document title "Deploy" in `docs/` folder (Is this the correct location?)
3. Main contributer of Superset gonna review my writing and write comment about it (Typo or other suggestion)
4. Everything seem fine, the PR got merged.

**Comment by 1c7** [comment]
## Current progress:
- [x] write a Dockerfile that base on Dockerhub `apache/superset`
Dockerfile
```
FROM apache/superset 
# ..etc
```

- [x] Install ClickHouse driver and use `superset_config.py` to config superset
```
FROM apache/superset 

USER root
RUN pip install clickhouse-driver==0.2.0 && pip install clickhouse-sqlalchemy==0.1.6
USER superset

COPY superset_config.py /app/pythonpath/superset_config.py
```

- [x] Figure out how to set PostgreSQL as Superset metadata database (instead of using default SQlite)

- [ ] Figure out what other component I need to config/setup
  - [ ] Caching with `CACHE_CONFIG` and `DATA_CACHE_CONFIG`
  - [ ] Celery for long running queries
  - [ ] Is there other component I am missing ?

- [ ] Deploy Superset on AWS ECS and make sure it work
- [ ] Write a document about my experiences & how to deploy
- [ ] Figure out where should I put the document inside Superset Github repository
- [ ] Send a Pull Request

**Comment by ad-m** [comment]
In the case of Celery, you have to consider transport.

You should be careful about volumes and analyze: https://github.com/apache/superset/blob/master/docker-compose-non-dev.yml

I suggest creating a draft PR, so feedback can be provided ongoing.

**Comment by ad-m** [comment]
Are you aware about ECS task definition of test env ( https://github.com/apache/superset/blob/master/.github/workflows/ecs-task-definition.json )?

**Comment by 1c7** [comment]
@ad-m That seems helpful, Let me check it out. Thanks!

**Comment by srinify** [comment]
Hi there @1c7 normally SIP's are for large, potentially controversial changes that require discussion & consensus building. But in this case, I would say there isn't much controversy :) 

If you'd like to contribute this documentation then you can open a PR and the community can review it! 

Also check out these other tutorials:

- https://towardsdatascience.com/running-apache-superset-at-scale-1539e3945093
- https://aws.amazon.com/quickstart/architecture/apache-superset/
- https://www.obytes.com/blog/apache-superset-on-aws-ecs

**Comment by 1c7** [comment]
@srinify Got it, Thank you!

**Comment by 1c7** [comment]
I am closing this issue because my focus has been shift to some other stuff.    
I successful deploy Superset onto AWS for my team to use.

**Comment by SahanSrinivas** [comment]
Hi @1c7 Can I know how did you deploy Apache Superset in AWS? or you can shed some light on the high level workflow which you did?

**Comment by 1c7** [comment]
@SahanSrinivas I deploy Superset on `AWS ECS` (China Region)

## 1. Write a Dockerfile
```dockerfile
FROM apache/superset:2.0.0

# Install ClickHouse driver
# Switching to root to install the required packages
USER root
RUN pip install clickhouse-driver==0.2.0 && pip install clickhouse-sqlalchemy==0.1.6
# Switching back to using the `superset` user
USER superset

# config file
COPY superset_config.py /app/pythonpath/superset_config.py
```

## 2. use `AWS Codebuild` to build the docker image,
so my `buildspec.yml` file look like this
```yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo 登录到 Amazon ECR...
      - $(aws ecr get-login --no-include-email --region cn-north-1)
      # https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html
      # 为了让 aws ecr get-login 命令能执行成功，请按照上面文档里给出的 policy 修改一下 IAM。
      # 添加这一段：
      # {
      #   "Action": [
      #     "ecr:BatchCheckLayerAvailability",
      #     "ecr:CompleteLayerUpload",
      #     "ecr:GetAuthorizationToken",
      #     "ecr:InitiateLayerUpload",
      #     "ecr:PutImage",
      #     "ecr:UploadLayerPart"
      #   ],
      #   "Resource": "*",
      #   "Effect": "Allow"
      # },
  build:
    commands:
      - echo Build 的开始时间是 `date`
      - echo 构建 Docker 镜像
      - docker build -t 832343096630.dkr.ecr.cn-north-1.amazonaws.com.cn/miracleplus-superset ./src/
  post_build:
    commands:
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - if [ $CODEBUILD_BUILD_SUCCEEDING == 0 ]; then echo "Build 步骤失败了"; exit 255; else echo "Build 步骤成功了"; fi
      - echo Build 完成时间 `date`
      - echo 开始推送 Docker Image 到 ECR
      - docker push 832343096630.dkr.ecr.cn-north-1.amazonaws.com.cn/miracleplus-superset

```

## 3. in the final step of Step 2, the docker image save to AWS ECR.

## 4. write a `ECS Task definitions`
* set `Image URI` as the ECR address like `832343096630.dkr.ecr.cn-north-1.amazonaws.com.cn/miracleplus-superset:latest`
* set environment variable like `DATABASE_PASSWORD` etc

## 5. last step, create a ECS cluster, create a service, use that task definition
