### ISSUE TITLE
Docker-Compose dev deployment can't change port and non-dev ignores config file settings.

### ISSUE THREAD

**Issue by jacobcroope** [apache/superset#18956]
I added `DASHBOARD_RBAC = True` to a working superset_docker_config.py configuration serving on port 80. 
`SUPERSET_WEBSERVER_PORT = 80`

The superset container served on 8088 every time regardless of config settings changes in .env, .env-non-dev, superset/config.py

changing .env-non-dev to 
`SUPERSET_PORT=80`
In addition to docker-compose-non-dev.yml 

```
  superset:
    env_file: docker/.env-non-dev
    image: *superset-image
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: unless-stopped
    ports:
      - 80:80
    depends_on: *superset-depends-on
    volumes: *superset-volumes

```

Made a non-dev container boot and serve on :80 

Launching docker-compose up for a dev version fails to start if you follow similar procedure. 

Only other potentially relevant bit of information is that `docker-compose build superset-websocket` had to be run to complete a non-dev build on port 8088. 

Clean git clone 

Python 3.8.10
Flask 1.1.4
Werkzeug 1.0.1
Superset 1.4.1

Clean clone as of 2/27/2022

- [] I have checked the superset logs for python stacktraces and included it here as text if there are any. I couldn't find these any guidance?  
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.
