### ISSUE TITLE
DB auth error when try to run helm chart v0.6.0

### ISSUE THREAD

**Issue by joaofelipecb** [apache/superset#19909]
When I tried to run helm chart v0.6.0, I notice that the db init job could not run. Also, I looked for logs of the postgres pod and I catched a authentication error.

```
2022-04-30 12:15:37.534 GMT [195] FATAL:  password authentication failed for user "superset"
2022-04-30 12:15:37.534 GMT [195] DETAIL:  Role "superset" does not exist.
        Connection matched pg_hba.conf line 1: "host     all
all             0.0.0.0/0               md5"
```

#### How to reproduce the bug

```
helm repo add superset https://apache.github.io/superset
helm upgrade --install --create-namespace --namespace superset superset superset/superset --version 0.6.0
kubectl get -n superset pod -w
```

Output:

```
NAME                              READY   STATUS             RESTARTS   AGE
superset-6d99875f75-wvvnr         1/1     Running            0          9m28s
superset-init-db-8smqz            0/1     Error              0          22s
superset-init-db-gd8wb            0/1     Error              0          39s
superset-init-db-xfchk            0/1     Error              0          32s
superset-postgresql-0             1/1     Running            0          9m28s
superset-redis-master-0           1/1     Running            0          9m28s
superset-worker-bb4d67447-ljbth   0/1     CrashLoopBackOff   6          9m28s
```

`kubectl logs superset-postgresql-0 -n superset`

Output:

```
2022-04-30 12:15:37.534 GMT [195] FATAL:  password authentication failed for user "superset"
2022-04-30 12:15:37.534 GMT [195] DETAIL:  Role "superset" does not exist.
        Connection matched pg_hba.conf line 1: "host     all
all             0.0.0.0/0               md5"
```

### Expected results

The database inicialization performs correctly via helm instalation.

### Actual results

The database inicialization doesn't perform correctly via helm instalation because of authentication error when try to connect to the postgresql database.

### Environment

(please complete the following information):

- browser type and version: N/A
- superset version: helm chart 0.6.0
- python version: Python 3.8.10
- node.js version: N/A
- any feature flags active:
- kubernetes version: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
- Helm Version: version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I notice that the helm chart was recently updated. In chart version 5.11.0 it works correctly.

**Comment by layoaster** [comment]
I'm also facing the same issue in version 0.6.1. I tried to pass secrets in two ways (`extraEnvRaw` and `envFromSecrets`) with no luck. The init job didn't pick them up:

```
Containers:
  superset-init-db:
    Container ID:  docker://a259a5e77e1a2dac05179fa4ef73afdb6f3db35174fcda57d041b7772d9147fc
    Image:         apache/superset:latest
    Image ID:      docker-pullable://apache/superset@sha256:14a31801f5f2180a7198a36c7044d75a91fa7d383091375aeb4b6c69e2713d5a
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
      . /app/pythonpath/superset_bootstrap.sh; . /app/pythonpath/superset_init.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 01 Jun 2022 09:12:54 +0100
      Finished:     Wed, 01 Jun 2022 09:13:03 +0100
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      superset-env  Secret  Optional: false
    Environment:    <none>
```

I can't understand what it's going on with the init-job template:

```yaml
containers:
    - name: {{ template "superset.name" . }}-init-db
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      {{- if or .Values.extraEnv .Values.extraEnvRaw }}
      env:
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.extraEnvRaw }}
        {{- toYaml .Values.extraEnvRaw | nindent 10 }}
        {{- end }}
      {{- end }}
      envFrom:
        - secretRef:
            name: {{ tpl .Values.envFromSecret . }}
        {{- range .Values.envFromSecrets }}
        - secretRef:
            name: {{ tpl . $ }}
        {{- end }}
```

**Comment by fedaeho** [comment]
Hi, I add `primary.initdb.user` and `primary.initdb.password` in `values.yaml` like below and it works.


```yaml
## Configuration values for the postgresql dependency.
## ref: https://github.com/kubernetes/charts/blob/master/stable/postgresql/README.md
postgresql:
  ...
  postgresqlPassword: superset
  ...
  primary:
    initdb:
      user: superset
      password: superset
   ...
```

**Comment by nytai** [comment]
Seems like the fix is to update the default values.yaml file with the above changes https://github.com/apache/superset/blob/4f9c2c8165ab5d875c14c7cd8e8585c78d45900f/helm/superset/values.yaml#L666

**Comment by RobertWan91** [comment]
> Seems like the fix is to update the default values.yaml file with the above changes
> 
> https://github.com/apache/superset/blob/4f9c2c8165ab5d875c14c7cd8e8585c78d45900f/helm/superset/values.yaml#L666

Hey there, I am facing the same issue using 0.7.7 version. But the above change doesn't seem to work for me.

I am using the

1. initdb change
2. manually set up the password via helm upgrade.

@joaofelipecb , in your additional context, do you mean chart version 0.5.11 work for you? Thanks.

**Comment by joaofelipecb** [comment]
@RobertWan91 , yes, it worked for me in version 0.5.11. Unfortunately, I wasn't able to download this version directly from helm, so I get it from github. Then, I installed in helm using the local repository directory.

I'm not sure, but I tried other version that worked correctly, maybe 0.6.1

**Comment by RobertWan91** [comment]
@joaofelipecb thanks for your reply. yeah I tried 0.5.11 from github but the dependency requires postgres chart 10.0.2 which is not available in bitnami... from superset 0.6.*, it uses postges 11.1.22 which doesn't work for me.

**Comment by m-ocean-it** [comment]
> > Seems like the fix is to update the default values.yaml file with the above changes
> > https://github.com/apache/superset/blob/4f9c2c8165ab5d875c14c7cd8e8585c78d45900f/helm/superset/values.yaml#L666
> 
> Hey there, I am facing the same issue using 0.7.7 version. But the above change doesn't seem to work for me.
> 
> I tried (but neither of them worked)
> 
>     1. initdb change as suggested [DB auth error when try to run helm chart v0.6.0 #19909 (comment)](https://github.com/apache/superset/issues/19909#issuecomment-1174629367)
> 
>     2. manually set up the password via helm upgrade.
> 
> 
> @joaofelipecb , in your additional context, do you mean chart version 0.5.11 work for you? Thanks.

Experiencing the same problem with chart versions `0.7.7.` and `0.8.10`.

**Comment by m-ocean-it** [comment]
After changing the `postgresql` field to what's shown below, I started getting another error.
```yaml
postgresql:
  postgresqlPassword: superset
  primary:
    initdb:
      user: superset
      password: superset
```

The database's logs stopped showing that `Role "superset" does not exist` error, instead, ending with `database system is ready to accept connections`. However, a Superset worker began failing with such message:
```
flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  password authentication failed for user "superset"
```
So, I updated the spec like this:
```yaml
postgresql:
  postgresqlPassword: superset
  primary:
    initdb:
      user: superset
      password: superset

supersetNode:
  connections:
    db_pass: superset
```
Alas, the error persisted. At last, I tried this below, but the error persisted, still:
```yaml
postgresql:
  postgresqlPassword: superset
  username: superset
  password: superset
  primary:
    initdb:
      user: superset
      password: superset

supersetNode:
  connections:
    db_pass: superset
```
