### ISSUE TITLE
Superset silently does not run queries with many databases

### ISSUE THREAD

**Issue by vivian-rook** [apache/superset#23855]
After adding 930 databases as data sources I'm finding that many of them will fail to have a query run against them. Seemingly doing nothing when the submit button is pressed. This seems to occur on databases added after 90. So the 90th database works, the 91st does not. Spot checking databases earlier in the series also seem to work, later do not appear to.

#### How to reproduce the bug
Add a lot of databases, at least 100. Do a query against the last database added.

### Expected results

Query to run, results to show.

### Actual results

A blue outline appears around the Run button indicating a click has happened then nothing happens, there is no loading icon, logs do not seem to change. Nothing on the screen appears to change.

### Environment

Superset is deployed to k8s with helm:
`helm install superset superset/superset -f values.yaml -f dbs.yaml`
values.yaml contains oauth information, dbs.yaml contains a long list of dbs:
```
extraConfigs:
  import_datasources.yaml: |
    databases:
    - database_name: aawiki
      password: <password>
      sqlalchemy_uri: mysql+mysqldb://<user>@aawiki.analytics.db.svc.eqiad.wmflabs:3306/aawiki_p?ssl=1
    - database_name: aawikibooks
      password: <password>
      sqlalchemy_uri: mysql+mysqldb://<user>@aawikibooks.analytics.db.svc.eqiad.wmflabs:3306/aawikibooks_p?ssl=1
    - database_name: aawiktionary
...
```
Firefox 112.0.2
Superset 2.0.1
Python 3.8.12
