### ISSUE TITLE
2.1.0 SQLab dropdown list is broken in impala connection

### ISSUE THREAD

**Issue by Heyzi** [apache/superset#24040]
Env: superset 2.1.0 installed via pip

Everything works fine on version 2.0.1, but after upgrading to version 2.1.0, dropdown list in SQL lab with impala connection stops working

Connection testing is successful on both versions 2.0.1 and 2.1.0 with current connection configuration:
```
database_name: Apache Impala
sqlalchemy_uri: impala://myhost
cache_timeout: null
expose_in_sqllab: true
allow_run_async: true
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_csv_upload: false
extra:
  allows_virtual_table_explore: true
  engine_params:
    connect_args:
      kerberos_service_name: impala
      auth_mechanism: GSSAPI
  metadata_params: {}
  cancel_query_on_windows_unload: true
  schemas_allowed_for_csv_upload: []
uuid: 4e3f5c07-09b2-49f5-92f2-1c200859bbfe
version: 1.0.0



```
>Connection looks good!

But in SQL, when loading a drop-down list lab i got this error:
<img width="1626" alt="1" src="https://github.com/apache/superset/assets/4046838/a5d69b54-f277-434c-9471-601a7d669262">
No errors or other messages in the logs.

At the same time select queries work fine. The only problem is with the dropdown list:
<img width="1626" alt="2" src="https://github.com/apache/superset/assets/4046838/817916c0-c951-473c-b98f-e41d502ba76a">

Python libs:
```
pyasn1-modules         0.3.0       
pycparser              2.20        
Pygments               2.15.1      
PyJWT                  2.4.0       
PyMeeus                0.5.11      
PyNaCl                 1.5.0       
pyparsing              3.0.6       
pyrsistent             0.16.1      
python-dateutil        2.8.2       
python-dotenv          0.19.0      
python-editor          1.0.4       
python-geohash         0.8.5       
python-ldap            3.4.0       
pytz                   2021.3      
PyYAML                 5.4.1       
redis                  3.5.3       
requests               2.28.1      
rich                   13.3.5      
selenium               3.141.0     
setuptools             67.7.2      
simplejson             3.17.3      
six                    1.16.0      
slack-sdk              3.18.3      
SQLAlchemy             1.4.36      
SQLAlchemy-Utils       0.38.3      
sqlparse               0.4.3       
sshtunnel              0.4.0       
tabulate               0.8.9       
thrift                 0.16.0      
thrift-sasl            0.4.3       
typing_extensions      4.4.0       
tzlocal                2.1         
urllib3                1.26.6      
vine                   5.0.0       
wcwidth                0.2.5       
webencodings           0.5.1       
Werkzeug               2.1.2       
wrapt                  1.15.0      
WTForms                2.3.3       
WTForms-JSON           0.3.3       
XlsxWriter             3.0.7       
zipp                   3.15.0      
zope.event             4.5.0       
zope.interface         5.4.0       
zstandard              0.21.0
 ```
