### ISSUE TITLE
Adding a FEATURE_FLAGS to Helm chart

### ISSUE THREAD

**Issue by alekseyolg** [apache/superset#24090]
I add in values.yaml:

```
extraConfigs:
  feature_flags.yaml: |
    FEATURE_FLAGS = { "DASHBOARD_RBAC": True }
```
The file appears in the pod's file system:

```
root@superset-6f9bfdd89b-79scs:/app# cat configs/feature_flags.yaml
FEATURE_FLAGS = { "DASHBOARD_RBAC": True }
```
Expected Behavior:
The feature works.

Real behavior:
Feature not working

**Comment by abhishekindigg** [comment]
@alekseyolg how did it work for you ? I'm also using Helm chart with custom values.yaml

**Comment by sharavara** [comment]
> @alekseyolg how did it work for you ? I'm also using Helm chart with custom values.yaml

Try this. It works for me


```yaml
configOverrides:
  secret: |
    SECRET_KEY = 'xxxyyyzzzz'
  fdfc_override: |
    FEATURE_FLAGS = {
        "DYNAMIC_PLUGINS": True,
        "DASHBOARD_RBAC": True
    }
    ```
