### ISSUE TITLE
Superset helm chart not following the resources setup 

### ISSUE THREAD

**Issue by rnpaiva** [apache/superset#26631]
#### How to reproduce the bug

Change the resources limits for the worker and deploy superset 3.0.2 in eks 

### Expected results
Resource limit as setup .

```
resources: 
    limits:
     cpu: 1
     memory: 3Gi
    requests:
     cpu: 1
     memory: 2Gi
```

what you expected to happen.

### Actual results
The workers are requesting a lot of memory and cpu that it's not setup . Superset it's running and I can open and create whatever I need , but the last worker it's having OOM .

#### Screenshots
( attached ) 
![Screenshot from 2024-01-16 10-44-48](https://github.com/apache/superset/assets/97540715/10c3f633-5be0-4558-979a-dac7b0f9d064)
![Screenshot from 2024-01-16 10-44-21](https://github.com/apache/superset/assets/97540715/c0669795-415b-4bd1-879d-c608666d49f8)
![Screenshot from 2024-01-16 10-44-11](https://github.com/apache/superset/assets/97540715/711b310b-c4d9-407d-bead-0c93b4a6f65e)
