### ISSUE TITLE
Resources for "wait-for-postgres"

### ISSUE THREAD

**Issue by julienLemarie** [apache/superset#32859]
### Bug description

Hello,

When I want to deploy superset, here is an extract of my values:

```superset:
  init:
    resources:
      requests:
        cpu: 0.1
        memory: 256Mi
      limits:
        cpu: 0.5
        memory: 512Mi
  resources:
    requests:
      cpu: 0.1
      memory: 256Mi
    limits:
      cpu: 0.5
      memory: 512Mi
```

but resources are not affected to the "wait-for-postgres" pod (and there is policies on my Kubernetes):

```
Error creating:   pods "connect-superset-init-db-zlc4c" is forbidden: failed quota: ***: must specify 
limits.cpu for: wait-for-postgres;
limits.memory for: wait-for-postgres; 
requests.cpu for: wait-for-postgres; 
requests.memory for: wait-for-postgres
```
I was thinking because  _wait-for-postgres_ `initContainers ` is in `init`, there was inheritance but seems not.

Any ideas ?

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by julienLemarie** [comment]
In fact, I already try to put directly explicitly resources values on the the wait-for-postgres `initContainer` even if it's not on the documentation but it's not working:

```
superset:
  init:
    resources:
      requests:
        cpu: 0.1
        memory: 256Mi
      limits:
        cpu: 0.5
        memory: 512Mi
  initContainers:
    - name: wait-for-postgres
      resources:
        requests:
          cpu: 0.1
          memory: 256Mi
        limits:
          cpu: 0.5
          memory: 512Mi
```
