### ISSUE TITLE
🐛 Bug: bootstrapScript does not install Trino connector, Trino option missing in Superset UI

### ISSUE THREAD

**Issue by helong001** [apache/superset#33691]
#### Description

When deploying Superset via the official Helm Chart, I attempted to install the Trino connector using the `bootstrapScript` with `uv pip install .[trino]`. However, after deployment, the Trino option does not appear in the UI under “+ Data” datasource options. It seems the bootstrap script is either not executed or does not take effect.

#### Relevant YAML snippet
```yaml
init:
  loadExamples: true

bootstrapScript: |
  #!/bin/bash
  uv pip install .[trino] &&
  if [ ! -f ~/bootstrap ]; then
    echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap
  fi
```

#### Expected Behavior
- The Trino connector should be installed via pip during bootstrap;
- Trino should appear as an option in the Superset UI datasource creation dialog;
- Superset should be able to connect to Trino backend without additional manual steps.

#### Actual Behavior
- Trino does not appear in the datasource list in UI;
- Checking inside the running pod, the ~/bootstrap file is missing, suggesting bootstrapScript was not run;
- Possibly the bootstrap script runs only once during initial image build or first pod start, but not on helm upgrades or helmfile apply.

### Superset version

4.1.2

### Python version

3.9

### Node version

I don't know

### Browser

Chrome

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.
